// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Example.Inputs
{

    public sealed class FooArgs : Pulumi.ResourceArgs
    {
        [Input("a")]
        public Input<bool>? A { get; set; }

        public FooArgs()
        {
        }
    }
}
