# Adds the ci/test-codegen label to a PR if this changes codegen.
# Keep CODEGEN_TEST_PACKAGES in scripts/get-job-matrix.py synced.
#
# Ref: https://github.com/actions/labeler
ci/test-codegen:
  - 'pkg/codegen/docs/**'
  - 'pkg/codegen/dotnet/**'
  - 'pkg/codegen/go/**'
  - 'pkg/codegen/nodejs/**'
  - 'pkg/codegen/python/**'
