#!/bin/bash

set -euo pipefail

>&2 echo "::group::Get version"
trap ">&2 echo '::endgroup::'" EXIT # bash equivalent of defer func()

# Remove whitespace, this is our version:
tr -d '[:space:]' < .version
