#!/usr/bin/env bash

set -euo pipefail

ROOT=$(dirname "${0}")/../..

if [ -n "${CI:-""}" ]; then
  >&2 echo "::group::Get version"
  trap ">&2 echo '::endgroup::'" EXIT # bash equivalent of defer func()
fi

# Remove whitespace, this is our version:
tr -d '[:space:]' < "${ROOT}/sdk/.version"
