#!/bin/bash

set -euo pipefail

>&2 echo "::group::Get version"
trap ">&2 echo '::endgroup::'" EXIT # bash equivalent of defer func()

PREVIOUS_VERSION="${1:-""}"
if [ -z "$PREVIOUS_VERSION" ]; then
  PREVIOUS_VERSION="$(.github/scripts/get-version)"
fi

if [[ "${PREVIOUS_VERSION}" = *-*.* ]]; then
  VERSION="${PREVIOUS_VERSION%.*}.$((${PREVIOUS_VERSION##*.} + 1))"
else
  IFS=. read -r major minor rest <<< "${PREVIOUS_VERSION}"
  VERSION="TAG=${major}.$((minor + 1)).0"
fi

echo -n "$VERSION"
