#!/usr/bin/env bash

set -euo pipefail

>&2 echo "::group::Get changelog"
trap ">&2 echo '::endgroup::'" EXIT # bash equivalent of defer func()

VERSION="${1:-""}"
if [ -z "${VERSION}" ]; then
  >&2 echo "::error::Version argument required."
  exit 1
fi

# Render all pending changelog entries for this version without writing files.
changie batch "${VERSION}" --dry-run
