replacements:
  - type: file
    file: ./sdk/.version
    fileFormat: sed
    updatePath: .*
    versionFormat: ${SEMVER}
  - type: file
    file: ./sdk/nodejs/package.json
    fileFormat: json
    updatePath: .version
    versionFormat: ${VERSION}
  - type: file
    file: ./npm/package.json
    fileFormat: json
    updatePath: .version
    versionFormat: ${VERSION}
  - type: file
    file: ./sdk/nodejs/version.ts
    fileFormat: sed
    updatePath: '^export const version = .*$'
    versionFormat: 'export const version = "${VERSION}";'
  - type: file
    file: ./sdk/python/lib/pulumi/_version.py
    fileFormat: sed
    updatePath: '^_VERSION = .*$'
    versionFormat: '_VERSION = "${VERSION}"'
  - type: file
    file: ./sdk/python/pyproject.toml
    fileFormat: sed
    updatePath: '^version = .*$'
    versionFormat: 'version = "${VERSION}"'
