# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .multi_argument_invoke import *
from .provider import *
from .string_resource import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "multi-argument-invoke",
  "mod": "index",
  "fqn": "pulumi_multi_argument_invoke",
  "classes": {
   "multi-argument-invoke:index:StringResource": "StringResource"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "multi-argument-invoke",
  "token": "pulumi:providers:multi-argument-invoke",
  "fqn": "pulumi_multi_argument_invoke",
  "class": "Provider"
 }
]
"""
)
