dist: goreleaser

project_name: pulumi

before:
  hooks:
    - ./scripts/prep-for-goreleaser.sh

blobs:
- bucket: get.pulumi.com
  folder: releases/sdk/
  ids:
    - pulumi-unix
    - pulumi-windows
  provider: s3
  region: us-west-2

release:
  disable: true

changelog:
  skip: true

builds:
- id: pulumi-unix
  binary: pulumi
  builder: prebuilt
  goos: ['linux', 'darwin']
  goarch: ['amd64', 'arm64']
  goamd64: ['v1']
  prebuilt:
    path: goreleaser-{{ .Os }}/pulumi-unix_{{ .Os }}_{{ .Arch }}{{ with .Amd64 }}_{{ . }}{{ end }}/pulumi
  mod_timestamp: '{{ .CommitTimestamp }}'
- id: pulumi-windows
  binary: pulumi
  builder: prebuilt
  goos: ['windows']
  goarch: ['amd64']
  goamd64: ['v1']
  prebuilt:
    path: goreleaser-{{ .Os }}/pulumi-windows_{{ .Os }}_{{ .Arch }}{{ with .Amd64 }}_{{ . }}{{ end }}/pulumi.exe
  mod_timestamp: '{{ .CommitTimestamp }}'
- id: pulumi-language-go-unix
  binary: pulumi-language-go
  builder: prebuilt
  goos: ['linux', 'darwin']
  goarch: ['amd64', 'arm64']
  goamd64: ['v1']
  prebuilt:
    path: goreleaser-{{ .Os }}/pulumi-language-go-unix_{{ .Os }}_{{ .Arch }}{{ with .Amd64 }}_{{ . }}{{ end }}/pulumi-language-go
  mod_timestamp: '{{ .CommitTimestamp }}'
- id: pulumi-language-go-windows
  binary: pulumi-language-go
  builder: prebuilt
  goos: ['windows']
  goarch: ['amd64']
  goamd64: ['v1']
  prebuilt:
    path: goreleaser-{{ .Os }}/pulumi-language-go-windows_{{ .Os }}_{{ .Arch }}{{ with .Amd64 }}_{{ . }}{{ end }}/pulumi-language-go.exe
  mod_timestamp: '{{ .CommitTimestamp }}'
- id: pulumi-language-nodejs-unix
  binary: pulumi-language-nodejs
  builder: prebuilt
  goos: ['linux', 'darwin']
  goarch: ['amd64', 'arm64']
  goamd64: ['v1']
  prebuilt:
    path: goreleaser-{{ .Os }}/pulumi-language-nodejs-unix_{{ .Os }}_{{ .Arch }}{{ with .Amd64 }}_{{ . }}{{ end }}/pulumi-language-nodejs
  mod_timestamp: '{{ .CommitTimestamp }}'
- id: pulumi-language-nodejs-windows
  binary: pulumi-language-nodejs
  builder: prebuilt
  goos: ['windows']
  goarch: ['amd64']
  goamd64: ['v1']
  prebuilt:
    path: goreleaser-{{ .Os }}/pulumi-language-nodejs-windows_{{ .Os }}_{{ .Arch }}{{ with .Amd64 }}_{{ . }}{{ end }}/pulumi-language-nodejs.exe
  mod_timestamp: '{{ .CommitTimestamp }}'
- id: pulumi-language-python-unix
  binary: pulumi-language-python
  builder: prebuilt
  goos: ['linux', 'darwin']
  goarch: ['amd64', 'arm64']
  goamd64: ['v1']
  prebuilt:
    path: goreleaser-{{ .Os }}/pulumi-language-python-unix_{{ .Os }}_{{ .Arch }}{{ with .Amd64 }}_{{ . }}{{ end }}/pulumi-language-python
  mod_timestamp: '{{ .CommitTimestamp }}'
- id: pulumi-language-python-windows
  binary: pulumi-language-python
  builder: prebuilt
  goos: ['windows']
  goarch: ['amd64']
  goamd64: ['v1']
  prebuilt:
    path: goreleaser-{{ .Os }}/pulumi-language-python-windows_{{ .Os }}_{{ .Arch }}{{ with .Amd64 }}_{{ . }}{{ end }}/pulumi-language-python.exe
  mod_timestamp: '{{ .CommitTimestamp }}'
- id: pulumi-language-dotnet-unix
  binary: pulumi-language-dotnet
  builder: prebuilt
  goos: ['linux', 'darwin']
  goarch: ['amd64', 'arm64']
  goamd64: ['v1']
  prebuilt:
    path: goreleaser-{{ .Os }}/pulumi-language-dotnet-unix_{{ .Os }}_{{ .Arch }}{{ with .Amd64 }}_{{ . }}{{ end }}/pulumi-language-dotnet
  mod_timestamp: '{{ .CommitTimestamp }}'
- id: pulumi-language-dotnet-windows
  binary: pulumi-language-dotnet
  builder: prebuilt
  goos: ['windows']
  goarch: ['amd64']
  goamd64: ['v1']
  prebuilt:
    path: goreleaser-{{ .Os }}/pulumi-language-dotnet-windows_{{ .Os }}_{{ .Arch }}{{ with .Amd64 }}_{{ . }}{{ end }}/pulumi-language-dotnet.exe
  mod_timestamp: '{{ .CommitTimestamp }}'
- id: pulumi-language-java-unix
  binary: pulumi-language-java
  builder: prebuilt
  goos: ['linux', 'darwin']
  goarch: ['amd64', 'arm64']
  goamd64: ['v1']
  prebuilt:
    path: goreleaser-lang/java/{{ .Os }}-{{ replace .Arch "amd64" "x64" }}/pulumi-language-java
  mod_timestamp: '{{ .CommitTimestamp }}'
- id: pulumi-language-java-windows
  binary: pulumi-language-java
  builder: prebuilt
  goos: ['windows']
  goarch: ['amd64']
  goamd64: ['v1']
  prebuilt:
    path: goreleaser-lang/java/{{ .Os }}-{{ replace .Arch "amd64" "x64" }}/pulumi-language-java.exe
  mod_timestamp: '{{ .CommitTimestamp }}'
- id: pulumi-language-yaml-unix
  binary: pulumi-language-yaml
  builder: prebuilt
  goos: ['linux', 'darwin']
  goarch: ['amd64', 'arm64']
  goamd64: ['v1']
  prebuilt:
    path: goreleaser-lang/yaml/{{ .Os }}-{{ replace .Arch "amd64" "x64" }}/pulumi-language-yaml
  mod_timestamp: '{{ .CommitTimestamp }}'
- id: pulumi-language-yaml-windows
  binary: pulumi-language-yaml
  builder: prebuilt
  goos: ['windows']
  goarch: ['amd64']
  goamd64: ['v1']
  prebuilt:
    path: goreleaser-lang/yaml/{{ .Os }}-{{ replace .Arch "amd64" "x64" }}/pulumi-language-yaml.exe
  mod_timestamp: '{{ .CommitTimestamp }}'

archives:
- id: pulumi-unix
  wrap_in_directory: pulumi
  builds:
    - pulumi-language-dotnet-unix
    - pulumi-language-go-unix
    - pulumi-language-python-unix
    - pulumi-language-nodejs-unix
    - pulumi-language-java-unix
    - pulumi-language-yaml-unix
    - pulumi-unix
  replacements:
    amd64: x64
  files:
    - pulumi-resource-pulumi-nodejs
    - pulumi-resource-pulumi-python
    - pulumi-analyzer-policy
    - pulumi-analyzer-policy-python
    - pulumi-language-python-exec
  name_template: "{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
- id: pulumi-windows
  wrap_in_directory: pulumi/bin
  builds:
    - pulumi-language-dotnet-windows
    - pulumi-language-go-windows
    - pulumi-language-python-windows
    - pulumi-language-nodejs-windows
    - pulumi-language-java-windows
    - pulumi-language-yaml-windows
    - pulumi-windows
  replacements:
    amd64: x64
  format: zip
  files:
    - pulumi-resource-pulumi-nodejs.cmd
    - pulumi-resource-pulumi-python.cmd
    - pulumi-python3-shim.cmd
    - pulumi-python-shim.cmd
    - pulumi-analyzer-policy.cmd
    - pulumi-analyzer-policy-python.cmd
    - pulumi-language-python-exec
  name_template: "{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"

snapshot:
  name_template: "{{ .Version }}-SNAPSHOT"

checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.txt"
