dist: goreleaser

project_name: pulumi

before:
  hooks:
    - ./scripts/get-language-providers.sh
    - ./scripts/prep-for-goreleaser.sh

release:
  disable: true

changelog:
  skip: true

builds:

- &pulumibin
  id: pulumi
  binary: pulumi
  dir: pkg
  main: ./cmd/pulumi
  gobinary: ../scripts/go-wrapper.sh
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goos: ['linux', 'darwin', 'windows']
  goarch: ['amd64', 'arm64']
  goamd64: ['v1']
  ignore:
    - goos: windows
      goarch: arm64
  ldflags:
    - -X github.com/pulumi/pulumi/pkg/v3/version.Version={{.Tag}}
  mod_timestamp: '{{ .CommitTimestamp }}'
- <<: *pulumibin
  id: pulumi-language-go
  binary: pulumi-language-go
  dir: sdk
  main: ./go/pulumi-language-go
- <<: *pulumibin
  id: pulumi-language-nodejs
  binary: pulumi-language-nodejs
  dir: sdk
  main: ./nodejs/cmd/pulumi-language-nodejs
- <<: *pulumibin
  id: pulumi-language-python
  binary: pulumi-language-python
  dir: sdk
  main: ./python/cmd/pulumi-language-python
- <<: *pulumibin
  id: pulumi-language-dotnet
  binary: pulumi-language-dotnet
  dir: sdk
  main: ./dotnet/cmd/pulumi-language-dotnet
- <<: *pulumibin
  id: pulumi-language-java
  binary: pulumi-language-java
  builder: prebuilt
  prebuilt:
    path: goreleaser-lang/java/{{ .Os }}-{{ replace .Arch "amd64" "x64" }}/{{ .Name }}
- <<: *pulumibin
  id: pulumi-language-yaml
  binary: pulumi-language-yaml
  builder: prebuilt
  prebuilt:
    path: goreleaser-lang/yaml/{{ .Os }}-{{ replace .Arch "amd64" "x64" }}/{{ .Name }}

archives:
- id: pulumi
  wrap_in_directory: pulumi{{ if eq .Os "windows" }}/bin{{ end }}
  format_overrides:
    - goos: windows
      format: zip
  replacements:
    amd64: x64
  files:
    - src: bin/{{ .Os }}/*
      dst: '.'
      strip_parent: true
  name_template: "{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"

snapshot:
  name_template: "{{ .Version }}-SNAPSHOT"

checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.txt"
