# .readthedocs.yaml
#
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - mkdir -p $READTHEDOCS_OUTPUT/html
    - pip install -r docs/requirements.txt
    - python -m sphinx -T -c docs/sphinx -b html -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/html
    - cp docs/sphinx/index.html.template $READTHEDOCS_OUTPUT/html/index.html

sphinx:
  configuration: docs/sphinx/conf.py

formats:
  - pdf

python:
  install:
    - requirements: docs/requirements.txt
