# .readthedocs.yaml
#
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
# Uv setup: https://docs.readthedocs.com/platform/stable/build-customization.html#install-dependencies-with-uv

version: 2
build:
  os: ubuntu-lts-latest
  tools:
    python: "3.14"
  jobs:
    pre_create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
    create_environment:
      - uv venv "${READTHEDOCS_VIRTUALENV_PATH}"
    install:
      - UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" uv sync --frozen --directory docs
    build:
      html:
        - make -C docs build

sphinx:
  configuration: docs/sphinx/conf.py

formats:
  - pdf
