// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export * from "./base";
import { Base } from "./base";

export { CustomArgs } from "./custom";
export type Custom = import("./custom").Custom;
export const Custom: typeof import("./custom").Custom = null as any;
utilities.lazyLoad(exports, ["Custom"], () => require("./custom"));

export { DerivedArgs } from "./derived";
export type Derived = import("./derived").Derived;
export const Derived: typeof import("./derived").Derived = null as any;
utilities.lazyLoad(exports, ["Derived"], () => require("./derived"));

export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "inherit:index:Base":
                return new Base(name, <any>undefined, { urn })
            case "inherit:index:Custom":
                return new Custom(name, <any>undefined, { urn })
            case "inherit:index:Derived":
                return new Derived(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("inherit", "index", _module)
pulumi.runtime.registerResourcePackage("inherit", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:inherit") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
