// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package flaky

import (
	"context"
	"reflect"

	"example.com/pulumi-flaky/sdk/go/v46/flaky/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type FlakyCreate struct {
	pulumi.CustomResourceState
}

// NewFlakyCreate registers a new resource with the given unique name, arguments, and options.
func NewFlakyCreate(ctx *pulumi.Context,
	name string, args *FlakyCreateArgs, opts ...pulumi.ResourceOption) (*FlakyCreate, error) {
	if args == nil {
		args = &FlakyCreateArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource FlakyCreate
	err := ctx.RegisterResource("flaky:index:FlakyCreate", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetFlakyCreate gets an existing FlakyCreate resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetFlakyCreate(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *FlakyCreateState, opts ...pulumi.ResourceOption) (*FlakyCreate, error) {
	var resource FlakyCreate
	err := ctx.ReadResource("flaky:index:FlakyCreate", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering FlakyCreate resources.
type flakyCreateState struct {
}

type FlakyCreateState struct {
}

func (FlakyCreateState) ElementType() reflect.Type {
	return reflect.TypeOf((*flakyCreateState)(nil)).Elem()
}

type flakyCreateArgs struct {
}

// The set of arguments for constructing a FlakyCreate resource.
type FlakyCreateArgs struct {
}

func (FlakyCreateArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*flakyCreateArgs)(nil)).Elem()
}

type FlakyCreateInput interface {
	pulumi.Input

	ToFlakyCreateOutput() FlakyCreateOutput
	ToFlakyCreateOutputWithContext(ctx context.Context) FlakyCreateOutput
}

func (*FlakyCreate) ElementType() reflect.Type {
	return reflect.TypeOf((**FlakyCreate)(nil)).Elem()
}

func (i *FlakyCreate) ToFlakyCreateOutput() FlakyCreateOutput {
	return i.ToFlakyCreateOutputWithContext(context.Background())
}

func (i *FlakyCreate) ToFlakyCreateOutputWithContext(ctx context.Context) FlakyCreateOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FlakyCreateOutput)
}

type FlakyCreateOutput struct{ *pulumi.OutputState }

func (FlakyCreateOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**FlakyCreate)(nil)).Elem()
}

func (o FlakyCreateOutput) ToFlakyCreateOutput() FlakyCreateOutput {
	return o
}

func (o FlakyCreateOutput) ToFlakyCreateOutputWithContext(ctx context.Context) FlakyCreateOutput {
	return o
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*FlakyCreateInput)(nil)).Elem(), &FlakyCreate{})
	pulumi.RegisterOutputType(FlakyCreateOutput{})
}
