# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'TopLevelArgs',
    'TopLevelArgsDict',
]

MYPY = False

if not MYPY:
    class TopLevelArgsDict(TypedDict):
        buzz: NotRequired[pulumi.Input[builtins.str]]
elif False:
    TopLevelArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class TopLevelArgs:
    def __init__(__self__, *,
                 buzz: Optional[pulumi.Input[builtins.str]] = None):
        if buzz is not None:
            pulumi.set(__self__, "buzz", buzz)

    @property
    @pulumi.getter
    def buzz(self) -> Optional[pulumi.Input[builtins.str]]:
        return pulumi.get(self, "buzz")

    @buzz.setter
    def buzz(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "buzz", value)


