// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface Tb1Args {
    x?: pulumi.Input<boolean>;
}

export interface Tb2Args {
    x?: pulumi.Input<boolean>;
}

export interface Tb3Args {
    x?: pulumi.Input<boolean>;
}

export interface Ti1Args {
    x?: pulumi.Input<number>;
}

export interface Ti2Args {
    x?: pulumi.Input<number>;
}

export interface Ti3Args {
    x?: pulumi.Input<number>;
}

export interface Tn1Args {
    x?: pulumi.Input<number>;
}

export interface Tn2Args {
    x?: pulumi.Input<number>;
}

export interface Tn3Args {
    x?: pulumi.Input<number>;
}

export interface Ts1Args {
    x?: pulumi.Input<string>;
}

export interface Ts2Args {
    x?: pulumi.Input<string>;
}

export interface Ts3Args {
    x?: pulumi.Input<string>;
}
