// *** WARNING: this file was generated by the Coconut IDL Compiler (CIDLC).  ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ec2

import (
    "errors"

    pbempty "github.com/golang/protobuf/ptypes/empty"
    pbstruct "github.com/golang/protobuf/ptypes/struct"
    "golang.org/x/net/context"

    "github.com/pulumi/coconut/pkg/resource"
    "github.com/pulumi/coconut/pkg/tokens"
    "github.com/pulumi/coconut/pkg/util/contract"
    "github.com/pulumi/coconut/pkg/util/mapper"
    "github.com/pulumi/coconut/sdk/go/pkg/cocorpc"
)

/* RPC stubs for VPCPeeringConnection resource provider */

// VPCPeeringConnectionToken is the type token corresponding to the VPCPeeringConnection package type.
const VPCPeeringConnectionToken = tokens.Type("aws:ec2/vpcPeeringConnection:VPCPeeringConnection")

// VPCPeeringConnectionProviderOps is a pluggable interface for VPCPeeringConnection-related management functionality.
type VPCPeeringConnectionProviderOps interface {
    Check(ctx context.Context, obj *VPCPeeringConnection) ([]mapper.FieldError, error)
    Create(ctx context.Context, obj *VPCPeeringConnection) (string, error)
    Get(ctx context.Context, id string) (*VPCPeeringConnection, error)
    InspectChange(ctx context.Context,
        id string, old *VPCPeeringConnection, new *VPCPeeringConnection, diff *resource.ObjectDiff) ([]string, error)
    Update(ctx context.Context,
        id string, old *VPCPeeringConnection, new *VPCPeeringConnection, diff *resource.ObjectDiff) error
    Delete(ctx context.Context, id string) error
}

// VPCPeeringConnectionProvider is a dynamic gRPC-based plugin for managing VPCPeeringConnection resources.
type VPCPeeringConnectionProvider struct {
    ops VPCPeeringConnectionProviderOps
}

// NewVPCPeeringConnectionProvider allocates a resource provider that delegates to a ops instance.
func NewVPCPeeringConnectionProvider(ops VPCPeeringConnectionProviderOps) cocorpc.ResourceProviderServer {
    contract.Assert(ops != nil)
    return &VPCPeeringConnectionProvider{ops: ops}
}

func (p *VPCPeeringConnectionProvider) Check(
    ctx context.Context, req *cocorpc.CheckRequest) (*cocorpc.CheckResponse, error) {
    contract.Assert(req.GetType() == string(VPCPeeringConnectionToken))
    obj, _, decerr := p.Unmarshal(req.GetProperties())
    if decerr == nil || len(decerr.Failures()) == 0 {
        failures, err := p.ops.Check(ctx, obj)
        if err != nil {
            return nil, err
        }
        if len(failures) > 0 {
            decerr = mapper.NewDecodeErr(failures)
        }
    }
    return resource.NewCheckResponse(decerr), nil
}

func (p *VPCPeeringConnectionProvider) Name(
    ctx context.Context, req *cocorpc.NameRequest) (*cocorpc.NameResponse, error) {
    contract.Assert(req.GetType() == string(VPCPeeringConnectionToken))
    obj, _, decerr := p.Unmarshal(req.GetProperties())
    if decerr != nil {
        return nil, decerr
    }
    if obj.Name == "" {
        return nil, errors.New("Name property cannot be empty")
    }
    return &cocorpc.NameResponse{Name: obj.Name}, nil
}

func (p *VPCPeeringConnectionProvider) Create(
    ctx context.Context, req *cocorpc.CreateRequest) (*cocorpc.CreateResponse, error) {
    contract.Assert(req.GetType() == string(VPCPeeringConnectionToken))
    obj, _, decerr := p.Unmarshal(req.GetProperties())
    if decerr != nil {
        return nil, decerr
    }
    id, err := p.ops.Create(ctx, obj)
    if err != nil {
        return nil, err
    }
    return &cocorpc.CreateResponse{
        Id:   id,
    }, nil
}

func (p *VPCPeeringConnectionProvider) Get(
    ctx context.Context, req *cocorpc.GetRequest) (*cocorpc.GetResponse, error) {
    contract.Assert(req.GetType() == string(VPCPeeringConnectionToken))
    id := req.GetId()
    obj, err := p.ops.Get(ctx, id)
    if err != nil {
        return nil, err
    }
    return &cocorpc.GetResponse{
        Properties: resource.MarshalProperties(
            nil, resource.NewPropertyMap(obj), resource.MarshalOptions{}),
    }, nil
}

func (p *VPCPeeringConnectionProvider) InspectChange(
    ctx context.Context, req *cocorpc.ChangeRequest) (*cocorpc.InspectChangeResponse, error) {
    contract.Assert(req.GetType() == string(VPCPeeringConnectionToken))
    old, oldprops, decerr := p.Unmarshal(req.GetOlds())
    if decerr != nil {
        return nil, decerr
    }
    new, newprops, decerr := p.Unmarshal(req.GetNews())
    if decerr != nil {
        return nil, decerr
    }
    diff := oldprops.Diff(newprops)
    var replaces []string
    if diff.Changed("name") {
        replaces = append(replaces, "name")
    }
    if diff.Changed("peerVpc") {
        replaces = append(replaces, "peerVpc")
    }
    if diff.Changed("vpc") {
        replaces = append(replaces, "vpc")
    }
    more, err := p.ops.InspectChange(ctx, req.GetId(), old, new, diff)
    if err != nil {
        return nil, err
    }
    return &cocorpc.InspectChangeResponse{
        Replaces: append(replaces, more...),
    }, err
}

func (p *VPCPeeringConnectionProvider) Update(
    ctx context.Context, req *cocorpc.ChangeRequest) (*pbempty.Empty, error) {
    contract.Assert(req.GetType() == string(VPCPeeringConnectionToken))
    old, oldprops, err := p.Unmarshal(req.GetOlds())
    if err != nil {
        return nil, err
    }
    new, newprops, err := p.Unmarshal(req.GetNews())
    if err != nil {
        return nil, err
    }
    diff := oldprops.Diff(newprops)
    if err := p.ops.Update(ctx, req.GetId(), old, new, diff); err != nil {
        return nil, err
    }
    return &pbempty.Empty{}, nil
}

func (p *VPCPeeringConnectionProvider) Delete(
    ctx context.Context, req *cocorpc.DeleteRequest) (*pbempty.Empty, error) {
    contract.Assert(req.GetType() == string(VPCPeeringConnectionToken))
    if err := p.ops.Delete(ctx, req.GetId()); err != nil {
        return nil, err
    }
    return &pbempty.Empty{}, nil
}

func (p *VPCPeeringConnectionProvider) Unmarshal(
    v *pbstruct.Struct) (*VPCPeeringConnection, resource.PropertyMap, mapper.DecodeError) {
    var obj VPCPeeringConnection
    props := resource.UnmarshalProperties(v)
    result := mapper.MapIU(props.Mappable(), &obj)
    return &obj, props, result
}

/* Marshalable VPCPeeringConnection structure(s) */

// VPCPeeringConnection is a marshalable representation of its corresponding IDL type.
type VPCPeeringConnection struct {
    Name string `json:"name"`
    PeerVPC *resource.ID `json:"peerVpc"`
    VPC *resource.ID `json:"vpc"`
}

// VPCPeeringConnection's properties have constants to make dealing with diffs and property bags easier.
const (
    VPCPeeringConnection_Name = "name"
    VPCPeeringConnection_PeerVPC = "peerVpc"
    VPCPeeringConnection_VPC = "vpc"
)


