# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'InnerType',
]

@pulumi.output_type
class InnerType(dict):
    """
    It's fine to use urn and id in nested objects
    """
    def __init__(__self__, *,
                 id: Optional[_builtins.str] = None,
                 urn: Optional[_builtins.str] = None):
        """
        It's fine to use urn and id in nested objects
        """
        if id is not None:
            pulumi.set(__self__, "id", id)
        if urn is not None:
            pulumi.set(__self__, "urn", urn)

    @_builtins.property
    @pulumi.getter
    def id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def urn(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "urn")


