// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package inheritabstract

import (
	"context"
	"reflect"

	"errors"
	"example.com/pulumi-inheritabstract/sdk/go/inheritabstract/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A concrete component that extends AbstractBase.
type ConcreteChild struct {
	AbstractBase

	ConcreteOutput pulumi.StringOutput `pulumi:"concreteOutput"`
}

// NewConcreteChild registers a new resource with the given unique name, arguments, and options.
func NewConcreteChild(ctx *pulumi.Context,
	name string, args *ConcreteChildArgs, opts ...pulumi.ResourceOption) (*ConcreteChild, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Extra == nil {
		return nil, errors.New("invalid value for required argument 'Extra'")
	}
	if args.Seed == nil {
		return nil, errors.New("invalid value for required argument 'Seed'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ConcreteChild
	err := ctx.RegisterRemoteComponentResource("inheritabstract:index:ConcreteChild", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// ConstructConcreteChildBase constructs ConcreteChild as a base of a user-authored derived component. Embed ConcreteChild in
// your component and call this after ctx.RegisterComponentResource to run the base construction
// through the engine and resolve the base outputs onto the embedded struct.
func ConstructConcreteChildBase(ctx *pulumi.Context, self pulumi.ComponentResource, args *ConcreteChildArgs) error {
	return ctx.ConstructBase(self, "inheritabstract:index:ConcreteChild", args, "", internal.PkgResourceDefaultOpts(nil)...)
}

type concreteChildArgs struct {
	Extra string `pulumi:"extra"`
	Seed  string `pulumi:"seed"`
}

// The set of arguments for constructing a ConcreteChild resource.
type ConcreteChildArgs struct {
	Extra pulumi.StringInput
	Seed  pulumi.StringInput
}

func (ConcreteChildArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*concreteChildArgs)(nil)).Elem()
}

type ConcreteChildInput interface {
	pulumi.Input

	ToConcreteChildOutput() ConcreteChildOutput
	ToConcreteChildOutputWithContext(ctx context.Context) ConcreteChildOutput
}

func (*ConcreteChild) ElementType() reflect.Type {
	return reflect.TypeOf((**ConcreteChild)(nil)).Elem()
}

func (i *ConcreteChild) ToConcreteChildOutput() ConcreteChildOutput {
	return i.ToConcreteChildOutputWithContext(context.Background())
}

func (i *ConcreteChild) ToConcreteChildOutputWithContext(ctx context.Context) ConcreteChildOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ConcreteChildOutput)
}

type ConcreteChildOutput struct{ *pulumi.OutputState }

func (ConcreteChildOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ConcreteChild)(nil)).Elem()
}

func (o ConcreteChildOutput) ToConcreteChildOutput() ConcreteChildOutput {
	return o
}

func (o ConcreteChildOutput) ToConcreteChildOutputWithContext(ctx context.Context) ConcreteChildOutput {
	return o
}

func (o ConcreteChildOutput) AbstractOutput() pulumi.StringOutput {
	return o.ApplyT(func(v *ConcreteChild) pulumi.StringOutput { return v.AbstractOutput }).(pulumi.StringOutput)
}

func (o ConcreteChildOutput) ConcreteOutput() pulumi.StringOutput {
	return o.ApplyT(func(v *ConcreteChild) pulumi.StringOutput { return v.ConcreteOutput }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ConcreteChildInput)(nil)).Elem(), &ConcreteChild{})
	pulumi.RegisterOutputType(ConcreteChildOutput{})
}
