# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .component import *
from .my_function import *
from .provider import *
from ._inputs import *
from . import outputs
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "typedDictDisabledExample",
  "mod": "index",
  "fqn": "pulumi_typedDictDisabledExample",
  "classes": {
   "typedDictDisabledExample:index:Component": "Component"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "typedDictDisabledExample",
  "token": "pulumi:providers:typedDictDisabledExample",
  "fqn": "pulumi_typedDictDisabledExample",
  "class": "Provider"
 }
]
"""
)
