[env]
_.python.venv = { path = ".venv", create = true }

[settings]
python.uv_venv_auto = true

[tasks.install]
description = "Install dependencies"
run = "uv pip install ."

[tasks.lint]
description = "Lint with ruff and mypy"
run = "ruff check"
