[env]
_.python.venv = { path = ".venv" }

[tasks.install]
description = "Install dependencies"
run = "pip -v install ."

[tasks.lint]
description = "Lint with ruff and mypy"
run = '''
ruff check
MYPYPATH=./stubs mypy ./lib/pulumi
pyright
'''
