[tasks.install]
description = "Install dependencies"
run = "pip -vvv install ."

[tasks.lint]
description = "Lint with ruff and mypy"
run = '''
ruff check
MYPYPATH=./stubs mypy ./lib/pulumi
pyright
'''
