# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'Tb',
    'Tb1Args',
    'Tb2Args',
    'Tb3Args',
    'Ti',
    'Ti1Args',
    'Ti2Args',
    'Ti3Args',
    'Tn',
    'Tn1Args',
    'Tn2Args',
    'Tn3Args',
    'Ts',
    'Ts1Args',
    'Ts2Args',
    'Ts3Args',
]

@pulumi.input_type
class Tb:
    def __init__(__self__, *,
                 x: Optional[bool] = None):
        if x is not None:
            pulumi.set(__self__, "x", x)

    @property
    @pulumi.getter
    def x(self) -> Optional[bool]:
        return pulumi.get(self, "x")

    @x.setter
    def x(self, value: Optional[bool]):
        pulumi.set(self, "x", value)


@pulumi.input_type
class Tb1Args:
    def __init__(__self__, *,
                 x: Optional[pulumi.Input[bool]] = None):
        if x is not None:
            pulumi.set(__self__, "x", x)

    @property
    @pulumi.getter
    def x(self) -> Optional[pulumi.Input[bool]]:
        return pulumi.get(self, "x")

    @x.setter
    def x(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "x", value)


@pulumi.input_type
class Tb2Args:
    def __init__(__self__, *,
                 x: Optional[pulumi.Input[bool]] = None):
        if x is not None:
            pulumi.set(__self__, "x", x)

    @property
    @pulumi.getter
    def x(self) -> Optional[pulumi.Input[bool]]:
        return pulumi.get(self, "x")

    @x.setter
    def x(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "x", value)


@pulumi.input_type
class Tb3Args:
    def __init__(__self__, *,
                 x: Optional[pulumi.Input[bool]] = None):
        if x is not None:
            pulumi.set(__self__, "x", x)

    @property
    @pulumi.getter
    def x(self) -> Optional[pulumi.Input[bool]]:
        return pulumi.get(self, "x")

    @x.setter
    def x(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "x", value)


@pulumi.input_type
class Ti:
    def __init__(__self__, *,
                 x: Optional[int] = None):
        if x is not None:
            pulumi.set(__self__, "x", x)

    @property
    @pulumi.getter
    def x(self) -> Optional[int]:
        return pulumi.get(self, "x")

    @x.setter
    def x(self, value: Optional[int]):
        pulumi.set(self, "x", value)


@pulumi.input_type
class Ti1Args:
    def __init__(__self__, *,
                 x: Optional[pulumi.Input[int]] = None):
        if x is not None:
            pulumi.set(__self__, "x", x)

    @property
    @pulumi.getter
    def x(self) -> Optional[pulumi.Input[int]]:
        return pulumi.get(self, "x")

    @x.setter
    def x(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "x", value)


@pulumi.input_type
class Ti2Args:
    def __init__(__self__, *,
                 x: Optional[pulumi.Input[int]] = None):
        if x is not None:
            pulumi.set(__self__, "x", x)

    @property
    @pulumi.getter
    def x(self) -> Optional[pulumi.Input[int]]:
        return pulumi.get(self, "x")

    @x.setter
    def x(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "x", value)


@pulumi.input_type
class Ti3Args:
    def __init__(__self__, *,
                 x: Optional[pulumi.Input[int]] = None):
        if x is not None:
            pulumi.set(__self__, "x", x)

    @property
    @pulumi.getter
    def x(self) -> Optional[pulumi.Input[int]]:
        return pulumi.get(self, "x")

    @x.setter
    def x(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "x", value)


@pulumi.input_type
class Tn:
    def __init__(__self__, *,
                 x: Optional[float] = None):
        if x is not None:
            pulumi.set(__self__, "x", x)

    @property
    @pulumi.getter
    def x(self) -> Optional[float]:
        return pulumi.get(self, "x")

    @x.setter
    def x(self, value: Optional[float]):
        pulumi.set(self, "x", value)


@pulumi.input_type
class Tn1Args:
    def __init__(__self__, *,
                 x: Optional[pulumi.Input[float]] = None):
        if x is not None:
            pulumi.set(__self__, "x", x)

    @property
    @pulumi.getter
    def x(self) -> Optional[pulumi.Input[float]]:
        return pulumi.get(self, "x")

    @x.setter
    def x(self, value: Optional[pulumi.Input[float]]):
        pulumi.set(self, "x", value)


@pulumi.input_type
class Tn2Args:
    def __init__(__self__, *,
                 x: Optional[pulumi.Input[float]] = None):
        if x is not None:
            pulumi.set(__self__, "x", x)

    @property
    @pulumi.getter
    def x(self) -> Optional[pulumi.Input[float]]:
        return pulumi.get(self, "x")

    @x.setter
    def x(self, value: Optional[pulumi.Input[float]]):
        pulumi.set(self, "x", value)


@pulumi.input_type
class Tn3Args:
    def __init__(__self__, *,
                 x: Optional[pulumi.Input[float]] = None):
        if x is not None:
            pulumi.set(__self__, "x", x)

    @property
    @pulumi.getter
    def x(self) -> Optional[pulumi.Input[float]]:
        return pulumi.get(self, "x")

    @x.setter
    def x(self, value: Optional[pulumi.Input[float]]):
        pulumi.set(self, "x", value)


@pulumi.input_type
class Ts:
    def __init__(__self__, *,
                 x: Optional[str] = None):
        if x is not None:
            pulumi.set(__self__, "x", x)

    @property
    @pulumi.getter
    def x(self) -> Optional[str]:
        return pulumi.get(self, "x")

    @x.setter
    def x(self, value: Optional[str]):
        pulumi.set(self, "x", value)


@pulumi.input_type
class Ts1Args:
    def __init__(__self__, *,
                 x: Optional[pulumi.Input[str]] = None):
        if x is not None:
            pulumi.set(__self__, "x", x)

    @property
    @pulumi.getter
    def x(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "x")

    @x.setter
    def x(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "x", value)


@pulumi.input_type
class Ts2Args:
    def __init__(__self__, *,
                 x: Optional[pulumi.Input[str]] = None):
        if x is not None:
            pulumi.set(__self__, "x", x)

    @property
    @pulumi.getter
    def x(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "x")

    @x.setter
    def x(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "x", value)


@pulumi.input_type
class Ts3Args:
    def __init__(__self__, *,
                 x: Optional[pulumi.Input[str]] = None):
        if x is not None:
            pulumi.set(__self__, "x", x)

    @property
    @pulumi.getter
    def x(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "x")

    @x.setter
    def x(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "x", value)


