// Copyright 2016-2023, Pulumi Corporation.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by "generate"; DO NOT EDIT.

//nolint:lll
package providers

import (
	"time"

	"github.com/pulumi/pulumi/sdk/v3/go/common/resource"
	pulumirpc "github.com/pulumi/pulumi/sdk/v3/proto/go"
	codegenrpc "github.com/pulumi/pulumi/sdk/v3/proto/go/codegen"
)

// Indicates that a call to check failed; it contains the property and reason for the failure.
type CheckFailure struct {
	// The property that failed validation.
	Property string
	// The reason that the property failed validation.
	Reason string
}

func (s *CheckFailure) marshal() *pulumirpc.CheckFailure {
	return &pulumirpc.CheckFailure{
		Property: s.Property,
		Reason:   s.Reason,
	}
}

func (s *CheckFailure) unmarshal(data *pulumirpc.CheckFailure) {
	s.Property = data.Property
	s.Reason = data.Reason
}
