// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package replaceonchanges

import (
	"context"
	"reflect"

	"errors"
	"example.com/pulumi-replaceonchanges/sdk/go/v25/replaceonchanges/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ResourceA struct {
	pulumi.CustomResourceState

	ReplaceProp pulumi.BoolPtrOutput `pulumi:"replaceProp"`
	Value       pulumi.BoolOutput    `pulumi:"value"`
}

// NewResourceA registers a new resource with the given unique name, arguments, and options.
func NewResourceA(ctx *pulumi.Context,
	name string, args *ResourceAArgs, opts ...pulumi.ResourceOption) (*ResourceA, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Value == nil {
		return nil, errors.New("invalid value for required argument 'Value'")
	}
	replaceOnChanges := pulumi.ReplaceOnChanges([]string{
		"replaceProp",
	})
	opts = append(opts, replaceOnChanges)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ResourceA
	err := ctx.RegisterResource("replaceonchanges:index:ResourceA", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetResourceA gets an existing ResourceA resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetResourceA(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ResourceAState, opts ...pulumi.ResourceOption) (*ResourceA, error) {
	var resource ResourceA
	err := ctx.ReadResource("replaceonchanges:index:ResourceA", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ResourceA resources.
type resourceAState struct {
}

type ResourceAState struct {
}

func (ResourceAState) ElementType() reflect.Type {
	return reflect.TypeOf((*resourceAState)(nil)).Elem()
}

type resourceAArgs struct {
	ReplaceProp *bool `pulumi:"replaceProp"`
	Value       bool  `pulumi:"value"`
}

// The set of arguments for constructing a ResourceA resource.
type ResourceAArgs struct {
	ReplaceProp pulumi.BoolPtrInput
	Value       pulumi.BoolInput
}

func (ResourceAArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*resourceAArgs)(nil)).Elem()
}

type ResourceAInput interface {
	pulumi.Input

	ToResourceAOutput() ResourceAOutput
	ToResourceAOutputWithContext(ctx context.Context) ResourceAOutput
}

func (*ResourceA) ElementType() reflect.Type {
	return reflect.TypeOf((**ResourceA)(nil)).Elem()
}

func (i *ResourceA) ToResourceAOutput() ResourceAOutput {
	return i.ToResourceAOutputWithContext(context.Background())
}

func (i *ResourceA) ToResourceAOutputWithContext(ctx context.Context) ResourceAOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ResourceAOutput)
}

// ResourceAArrayInput is an input type that accepts ResourceAArray and ResourceAArrayOutput values.
// You can construct a concrete instance of `ResourceAArrayInput` via:
//
//	ResourceAArray{ ResourceAArgs{...} }
type ResourceAArrayInput interface {
	pulumi.Input

	ToResourceAArrayOutput() ResourceAArrayOutput
	ToResourceAArrayOutputWithContext(context.Context) ResourceAArrayOutput
}

type ResourceAArray []ResourceAInput

func (ResourceAArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ResourceA)(nil)).Elem()
}

func (i ResourceAArray) ToResourceAArrayOutput() ResourceAArrayOutput {
	return i.ToResourceAArrayOutputWithContext(context.Background())
}

func (i ResourceAArray) ToResourceAArrayOutputWithContext(ctx context.Context) ResourceAArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ResourceAArrayOutput)
}

// ResourceAMapInput is an input type that accepts ResourceAMap and ResourceAMapOutput values.
// You can construct a concrete instance of `ResourceAMapInput` via:
//
//	ResourceAMap{ "key": ResourceAArgs{...} }
type ResourceAMapInput interface {
	pulumi.Input

	ToResourceAMapOutput() ResourceAMapOutput
	ToResourceAMapOutputWithContext(context.Context) ResourceAMapOutput
}

type ResourceAMap map[string]ResourceAInput

func (ResourceAMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ResourceA)(nil)).Elem()
}

func (i ResourceAMap) ToResourceAMapOutput() ResourceAMapOutput {
	return i.ToResourceAMapOutputWithContext(context.Background())
}

func (i ResourceAMap) ToResourceAMapOutputWithContext(ctx context.Context) ResourceAMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ResourceAMapOutput)
}

type ResourceAOutput struct{ *pulumi.OutputState }

func (ResourceAOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ResourceA)(nil)).Elem()
}

func (o ResourceAOutput) ToResourceAOutput() ResourceAOutput {
	return o
}

func (o ResourceAOutput) ToResourceAOutputWithContext(ctx context.Context) ResourceAOutput {
	return o
}

func (o ResourceAOutput) ReplaceProp() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ResourceA) pulumi.BoolPtrOutput { return v.ReplaceProp }).(pulumi.BoolPtrOutput)
}

func (o ResourceAOutput) Value() pulumi.BoolOutput {
	return o.ApplyT(func(v *ResourceA) pulumi.BoolOutput { return v.Value }).(pulumi.BoolOutput)
}

type ResourceAArrayOutput struct{ *pulumi.OutputState }

func (ResourceAArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ResourceA)(nil)).Elem()
}

func (o ResourceAArrayOutput) ToResourceAArrayOutput() ResourceAArrayOutput {
	return o
}

func (o ResourceAArrayOutput) ToResourceAArrayOutputWithContext(ctx context.Context) ResourceAArrayOutput {
	return o
}

func (o ResourceAArrayOutput) Index(i pulumi.IntInput) ResourceAOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ResourceA {
		return vs[0].([]*ResourceA)[vs[1].(int)]
	}).(ResourceAOutput)
}

type ResourceAMapOutput struct{ *pulumi.OutputState }

func (ResourceAMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ResourceA)(nil)).Elem()
}

func (o ResourceAMapOutput) ToResourceAMapOutput() ResourceAMapOutput {
	return o
}

func (o ResourceAMapOutput) ToResourceAMapOutputWithContext(ctx context.Context) ResourceAMapOutput {
	return o
}

func (o ResourceAMapOutput) MapIndex(k pulumi.StringInput) ResourceAOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ResourceA {
		return vs[0].(map[string]*ResourceA)[vs[1].(string)]
	}).(ResourceAOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ResourceAInput)(nil)).Elem(), &ResourceA{})
	pulumi.RegisterInputType(reflect.TypeOf((*ResourceAArrayInput)(nil)).Elem(), ResourceAArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ResourceAMapInput)(nil)).Elem(), ResourceAMap{})
	pulumi.RegisterOutputType(ResourceAOutput{})
	pulumi.RegisterOutputType(ResourceAArrayOutput{})
	pulumi.RegisterOutputType(ResourceAMapOutput{})
}
