# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import workflow_pb2 as pulumi_dot_workflow__pb2


class WorkflowEvaluatorStub(object):
    """WorkflowEvaluator is called by a scheduler/coordinator to ask a running workflow
    evaluator process to materialize graph shape and execute specific callable nodes.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateJob = channel.unary_unary(
                '/pulumirpc.WorkflowEvaluator/GenerateJob',
                request_serializer=pulumi_dot_workflow__pb2.GenerateJobRequest.SerializeToString,
                response_deserializer=pulumi_dot_workflow__pb2.GenerateNodeResponse.FromString,
                )
        self.GenerateGraph = channel.unary_unary(
                '/pulumirpc.WorkflowEvaluator/GenerateGraph',
                request_serializer=pulumi_dot_workflow__pb2.GenerateGraphRequest.SerializeToString,
                response_deserializer=pulumi_dot_workflow__pb2.GenerateNodeResponse.FromString,
                )
        self.RunSensor = channel.unary_unary(
                '/pulumirpc.WorkflowEvaluator/RunSensor',
                request_serializer=pulumi_dot_workflow__pb2.RunSensorRequest.SerializeToString,
                response_deserializer=pulumi_dot_workflow__pb2.RunSensorResponse.FromString,
                )
        self.RunStep = channel.unary_unary(
                '/pulumirpc.WorkflowEvaluator/RunStep',
                request_serializer=pulumi_dot_workflow__pb2.RunStepRequest.SerializeToString,
                response_deserializer=pulumi_dot_workflow__pb2.RunStepResponse.FromString,
                )
        self.RunFilter = channel.unary_unary(
                '/pulumirpc.WorkflowEvaluator/RunFilter',
                request_serializer=pulumi_dot_workflow__pb2.RunFilterRequest.SerializeToString,
                response_deserializer=pulumi_dot_workflow__pb2.RunFilterResponse.FromString,
                )
        self.RunOnError = channel.unary_unary(
                '/pulumirpc.WorkflowEvaluator/RunOnError',
                request_serializer=pulumi_dot_workflow__pb2.RunOnErrorRequest.SerializeToString,
                response_deserializer=pulumi_dot_workflow__pb2.RunOnErrorResponse.FromString,
                )


class WorkflowEvaluatorServicer(object):
    """WorkflowEvaluator is called by a scheduler/coordinator to ask a running workflow
    evaluator process to materialize graph shape and execute specific callable nodes.
    """

    def GenerateJob(self, request, context):
        """GenerateJob asks the evaluator to generate the job shape for a path.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateGraph(self, request, context):
        """GenerateGraph asks the evaluator to generate the graph/subgraph shape for a path.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunSensor(self, request, context):
        """RunSensor executes a sensor poll function and returns fire/skip plus cursor data.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunStep(self, request, context):
        """RunStep executes a single step and returns a PropertyValue-compatible result.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunFilter(self, request, context):
        """RunFilter executes a trigger filter and returns pass/fail.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunOnError(self, request, context):
        """RunOnError executes a node's on-error callback and returns retry behavior.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkflowEvaluatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateJob,
                    request_deserializer=pulumi_dot_workflow__pb2.GenerateJobRequest.FromString,
                    response_serializer=pulumi_dot_workflow__pb2.GenerateNodeResponse.SerializeToString,
            ),
            'GenerateGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateGraph,
                    request_deserializer=pulumi_dot_workflow__pb2.GenerateGraphRequest.FromString,
                    response_serializer=pulumi_dot_workflow__pb2.GenerateNodeResponse.SerializeToString,
            ),
            'RunSensor': grpc.unary_unary_rpc_method_handler(
                    servicer.RunSensor,
                    request_deserializer=pulumi_dot_workflow__pb2.RunSensorRequest.FromString,
                    response_serializer=pulumi_dot_workflow__pb2.RunSensorResponse.SerializeToString,
            ),
            'RunStep': grpc.unary_unary_rpc_method_handler(
                    servicer.RunStep,
                    request_deserializer=pulumi_dot_workflow__pb2.RunStepRequest.FromString,
                    response_serializer=pulumi_dot_workflow__pb2.RunStepResponse.SerializeToString,
            ),
            'RunFilter': grpc.unary_unary_rpc_method_handler(
                    servicer.RunFilter,
                    request_deserializer=pulumi_dot_workflow__pb2.RunFilterRequest.FromString,
                    response_serializer=pulumi_dot_workflow__pb2.RunFilterResponse.SerializeToString,
            ),
            'RunOnError': grpc.unary_unary_rpc_method_handler(
                    servicer.RunOnError,
                    request_deserializer=pulumi_dot_workflow__pb2.RunOnErrorRequest.FromString,
                    response_serializer=pulumi_dot_workflow__pb2.RunOnErrorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pulumirpc.WorkflowEvaluator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WorkflowEvaluator(object):
    """WorkflowEvaluator is called by a scheduler/coordinator to ask a running workflow
    evaluator process to materialize graph shape and execute specific callable nodes.
    """

    @staticmethod
    def GenerateJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pulumirpc.WorkflowEvaluator/GenerateJob',
            pulumi_dot_workflow__pb2.GenerateJobRequest.SerializeToString,
            pulumi_dot_workflow__pb2.GenerateNodeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pulumirpc.WorkflowEvaluator/GenerateGraph',
            pulumi_dot_workflow__pb2.GenerateGraphRequest.SerializeToString,
            pulumi_dot_workflow__pb2.GenerateNodeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RunSensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pulumirpc.WorkflowEvaluator/RunSensor',
            pulumi_dot_workflow__pb2.RunSensorRequest.SerializeToString,
            pulumi_dot_workflow__pb2.RunSensorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RunStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pulumirpc.WorkflowEvaluator/RunStep',
            pulumi_dot_workflow__pb2.RunStepRequest.SerializeToString,
            pulumi_dot_workflow__pb2.RunStepResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RunFilter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pulumirpc.WorkflowEvaluator/RunFilter',
            pulumi_dot_workflow__pb2.RunFilterRequest.SerializeToString,
            pulumi_dot_workflow__pb2.RunFilterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RunOnError(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pulumirpc.WorkflowEvaluator/RunOnError',
            pulumi_dot_workflow__pb2.RunOnErrorRequest.SerializeToString,
            pulumi_dot_workflow__pb2.RunOnErrorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class WorkflowRegistryStub(object):
    """WorkflowRegistry is called by workflow SDKs/plugins during startup to register
    exported workflow components (graphs/jobs/subgraphs/steps/functions), similar to
    how MLC packages register callable exports.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterComponent = channel.unary_unary(
                '/pulumirpc.WorkflowRegistry/RegisterComponent',
                request_serializer=pulumi_dot_workflow__pb2.RegisterComponentRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class WorkflowRegistryServicer(object):
    """WorkflowRegistry is called by workflow SDKs/plugins during startup to register
    exported workflow components (graphs/jobs/subgraphs/steps/functions), similar to
    how MLC packages register callable exports.
    """

    def RegisterComponent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkflowRegistryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterComponent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterComponent,
                    request_deserializer=pulumi_dot_workflow__pb2.RegisterComponentRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pulumirpc.WorkflowRegistry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WorkflowRegistry(object):
    """WorkflowRegistry is called by workflow SDKs/plugins during startup to register
    exported workflow components (graphs/jobs/subgraphs/steps/functions), similar to
    how MLC packages register callable exports.
    """

    @staticmethod
    def RegisterComponent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pulumirpc.WorkflowRegistry/RegisterComponent',
            pulumi_dot_workflow__pb2.RegisterComponentRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class GraphMonitorStub(object):
    """GraphMonitor is called while evaluating a concrete graph execution/generation.
    It records the graph shape for that evaluation and resolves prior node outputs.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterTrigger = channel.unary_unary(
                '/pulumirpc.GraphMonitor/RegisterTrigger',
                request_serializer=pulumi_dot_workflow__pb2.RegisterTriggerRequest.SerializeToString,
                response_deserializer=pulumi_dot_workflow__pb2.RegisterNodeResponse.FromString,
                )
        self.RegisterSensor = channel.unary_unary(
                '/pulumirpc.GraphMonitor/RegisterSensor',
                request_serializer=pulumi_dot_workflow__pb2.RegisterSensorRequest.SerializeToString,
                response_deserializer=pulumi_dot_workflow__pb2.RegisterNodeResponse.FromString,
                )
        self.RegisterJob = channel.unary_unary(
                '/pulumirpc.GraphMonitor/RegisterJob',
                request_serializer=pulumi_dot_workflow__pb2.RegisterJobRequest.SerializeToString,
                response_deserializer=pulumi_dot_workflow__pb2.RegisterNodeResponse.FromString,
                )
        self.RegisterGraph = channel.unary_unary(
                '/pulumirpc.GraphMonitor/RegisterGraph',
                request_serializer=pulumi_dot_workflow__pb2.RegisterGraphRequest.SerializeToString,
                response_deserializer=pulumi_dot_workflow__pb2.RegisterNodeResponse.FromString,
                )
        self.RegisterStep = channel.unary_unary(
                '/pulumirpc.GraphMonitor/RegisterStep',
                request_serializer=pulumi_dot_workflow__pb2.RegisterStepRequest.SerializeToString,
                response_deserializer=pulumi_dot_workflow__pb2.RegisterNodeResponse.FromString,
                )
        self.GetStepResult = channel.unary_unary(
                '/pulumirpc.GraphMonitor/GetStepResult',
                request_serializer=pulumi_dot_workflow__pb2.GetStepResultRequest.SerializeToString,
                response_deserializer=pulumi_dot_workflow__pb2.GetStepResultResponse.FromString,
                )


class GraphMonitorServicer(object):
    """GraphMonitor is called while evaluating a concrete graph execution/generation.
    It records the graph shape for that evaluation and resolves prior node outputs.
    """

    def RegisterTrigger(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterSensor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterStep(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStepResult(self, request, context):
        """GetStepResult asks for a previously completed step output.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GraphMonitorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterTrigger': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterTrigger,
                    request_deserializer=pulumi_dot_workflow__pb2.RegisterTriggerRequest.FromString,
                    response_serializer=pulumi_dot_workflow__pb2.RegisterNodeResponse.SerializeToString,
            ),
            'RegisterSensor': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterSensor,
                    request_deserializer=pulumi_dot_workflow__pb2.RegisterSensorRequest.FromString,
                    response_serializer=pulumi_dot_workflow__pb2.RegisterNodeResponse.SerializeToString,
            ),
            'RegisterJob': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterJob,
                    request_deserializer=pulumi_dot_workflow__pb2.RegisterJobRequest.FromString,
                    response_serializer=pulumi_dot_workflow__pb2.RegisterNodeResponse.SerializeToString,
            ),
            'RegisterGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterGraph,
                    request_deserializer=pulumi_dot_workflow__pb2.RegisterGraphRequest.FromString,
                    response_serializer=pulumi_dot_workflow__pb2.RegisterNodeResponse.SerializeToString,
            ),
            'RegisterStep': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterStep,
                    request_deserializer=pulumi_dot_workflow__pb2.RegisterStepRequest.FromString,
                    response_serializer=pulumi_dot_workflow__pb2.RegisterNodeResponse.SerializeToString,
            ),
            'GetStepResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStepResult,
                    request_deserializer=pulumi_dot_workflow__pb2.GetStepResultRequest.FromString,
                    response_serializer=pulumi_dot_workflow__pb2.GetStepResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pulumirpc.GraphMonitor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GraphMonitor(object):
    """GraphMonitor is called while evaluating a concrete graph execution/generation.
    It records the graph shape for that evaluation and resolves prior node outputs.
    """

    @staticmethod
    def RegisterTrigger(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pulumirpc.GraphMonitor/RegisterTrigger',
            pulumi_dot_workflow__pb2.RegisterTriggerRequest.SerializeToString,
            pulumi_dot_workflow__pb2.RegisterNodeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterSensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pulumirpc.GraphMonitor/RegisterSensor',
            pulumi_dot_workflow__pb2.RegisterSensorRequest.SerializeToString,
            pulumi_dot_workflow__pb2.RegisterNodeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pulumirpc.GraphMonitor/RegisterJob',
            pulumi_dot_workflow__pb2.RegisterJobRequest.SerializeToString,
            pulumi_dot_workflow__pb2.RegisterNodeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pulumirpc.GraphMonitor/RegisterGraph',
            pulumi_dot_workflow__pb2.RegisterGraphRequest.SerializeToString,
            pulumi_dot_workflow__pb2.RegisterNodeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pulumirpc.GraphMonitor/RegisterStep',
            pulumi_dot_workflow__pb2.RegisterStepRequest.SerializeToString,
            pulumi_dot_workflow__pb2.RegisterNodeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStepResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pulumirpc.GraphMonitor/GetStepResult',
            pulumi_dot_workflow__pb2.GetStepResultRequest.SerializeToString,
            pulumi_dot_workflow__pb2.GetStepResultResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
