from typing import Optional, Sequence, Any
import grpc


class Server:
    def add_insecure_port(self, address: str) -> int: ...
    async def start(self) -> None: ...
    async def stop(self, grace: Optional[float]) -> None: ...
    async def wait_for_termination(self, timeout: Optional[float]=...) -> bool: ...


def server(options: Any) -> Server: ...
