// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Mypkg.Outputs
{

    [OutputType]
    public sealed class Config
    {
        public readonly string? Foo;

        [OutputConstructor]
        private Config(string? foo)
        {
            Foo = foo;
        }
    }
}
