// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const Enum_XYZ = {
    Plain: "A",
    Snake_case: "B",
    SHA256: "C",
    SHA256_hash: "D",
} as const;

export type Enum_XYZ = (typeof Enum_XYZ)[keyof typeof Enum_XYZ];
