// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package discriminatedunion

import (
	"context"
	"reflect"

	"example.com/pulumi-discriminated-union/sdk/go/v31/discriminatedunion/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type VariantOne struct {
	DiscriminantKind string  `pulumi:"discriminantKind"`
	Field1           *string `pulumi:"field1"`
}

// VariantOneInput is an input type that accepts VariantOneArgs and VariantOneOutput values.
// You can construct a concrete instance of `VariantOneInput` via:
//
//	VariantOneArgs{...}
type VariantOneInput interface {
	pulumi.Input

	ToVariantOneOutput() VariantOneOutput
	ToVariantOneOutputWithContext(context.Context) VariantOneOutput
}

type VariantOneArgs struct {
	DiscriminantKind pulumi.StringInput    `pulumi:"discriminantKind"`
	Field1           pulumi.StringPtrInput `pulumi:"field1"`
}

func (VariantOneArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*VariantOne)(nil)).Elem()
}

func (i VariantOneArgs) ToVariantOneOutput() VariantOneOutput {
	return i.ToVariantOneOutputWithContext(context.Background())
}

func (i VariantOneArgs) ToVariantOneOutputWithContext(ctx context.Context) VariantOneOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VariantOneOutput)
}

func (i VariantOneArgs) ToVariantOnePtrOutput() VariantOnePtrOutput {
	return i.ToVariantOnePtrOutputWithContext(context.Background())
}

func (i VariantOneArgs) ToVariantOnePtrOutputWithContext(ctx context.Context) VariantOnePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VariantOneOutput).ToVariantOnePtrOutputWithContext(ctx)
}

// VariantOnePtrInput is an input type that accepts VariantOneArgs, VariantOnePtr and VariantOnePtrOutput values.
// You can construct a concrete instance of `VariantOnePtrInput` via:
//
//	        VariantOneArgs{...}
//
//	or:
//
//	        nil
type VariantOnePtrInput interface {
	pulumi.Input

	ToVariantOnePtrOutput() VariantOnePtrOutput
	ToVariantOnePtrOutputWithContext(context.Context) VariantOnePtrOutput
}

type variantOnePtrType VariantOneArgs

func VariantOnePtr(v *VariantOneArgs) VariantOnePtrInput {
	return (*variantOnePtrType)(v)
}

func (*variantOnePtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**VariantOne)(nil)).Elem()
}

func (i *variantOnePtrType) ToVariantOnePtrOutput() VariantOnePtrOutput {
	return i.ToVariantOnePtrOutputWithContext(context.Background())
}

func (i *variantOnePtrType) ToVariantOnePtrOutputWithContext(ctx context.Context) VariantOnePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VariantOnePtrOutput)
}

type VariantOneOutput struct{ *pulumi.OutputState }

func (VariantOneOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*VariantOne)(nil)).Elem()
}

func (o VariantOneOutput) ToVariantOneOutput() VariantOneOutput {
	return o
}

func (o VariantOneOutput) ToVariantOneOutputWithContext(ctx context.Context) VariantOneOutput {
	return o
}

func (o VariantOneOutput) ToVariantOnePtrOutput() VariantOnePtrOutput {
	return o.ToVariantOnePtrOutputWithContext(context.Background())
}

func (o VariantOneOutput) ToVariantOnePtrOutputWithContext(ctx context.Context) VariantOnePtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v VariantOne) *VariantOne {
		return &v
	}).(VariantOnePtrOutput)
}

func (o VariantOneOutput) DiscriminantKind() pulumi.StringOutput {
	return o.ApplyT(func(v VariantOne) string { return v.DiscriminantKind }).(pulumi.StringOutput)
}

func (o VariantOneOutput) Field1() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VariantOne) *string { return v.Field1 }).(pulumi.StringPtrOutput)
}

type VariantOnePtrOutput struct{ *pulumi.OutputState }

func (VariantOnePtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**VariantOne)(nil)).Elem()
}

func (o VariantOnePtrOutput) ToVariantOnePtrOutput() VariantOnePtrOutput {
	return o
}

func (o VariantOnePtrOutput) ToVariantOnePtrOutputWithContext(ctx context.Context) VariantOnePtrOutput {
	return o
}

func (o VariantOnePtrOutput) Elem() VariantOneOutput {
	return o.ApplyT(func(v *VariantOne) VariantOne {
		if v != nil {
			return *v
		}
		var ret VariantOne
		return ret
	}).(VariantOneOutput)
}

func (o VariantOnePtrOutput) DiscriminantKind() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VariantOne) *string {
		if v == nil {
			return nil
		}
		return &v.DiscriminantKind
	}).(pulumi.StringPtrOutput)
}

func (o VariantOnePtrOutput) Field1() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VariantOne) *string {
		if v == nil {
			return nil
		}
		return v.Field1
	}).(pulumi.StringPtrOutput)
}

type VariantTwo struct {
	DiscriminantKind string  `pulumi:"discriminantKind"`
	Field2           *string `pulumi:"field2"`
}

// VariantTwoInput is an input type that accepts VariantTwoArgs and VariantTwoOutput values.
// You can construct a concrete instance of `VariantTwoInput` via:
//
//	VariantTwoArgs{...}
type VariantTwoInput interface {
	pulumi.Input

	ToVariantTwoOutput() VariantTwoOutput
	ToVariantTwoOutputWithContext(context.Context) VariantTwoOutput
}

type VariantTwoArgs struct {
	DiscriminantKind pulumi.StringInput    `pulumi:"discriminantKind"`
	Field2           pulumi.StringPtrInput `pulumi:"field2"`
}

func (VariantTwoArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*VariantTwo)(nil)).Elem()
}

func (i VariantTwoArgs) ToVariantTwoOutput() VariantTwoOutput {
	return i.ToVariantTwoOutputWithContext(context.Background())
}

func (i VariantTwoArgs) ToVariantTwoOutputWithContext(ctx context.Context) VariantTwoOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VariantTwoOutput)
}

func (i VariantTwoArgs) ToVariantTwoPtrOutput() VariantTwoPtrOutput {
	return i.ToVariantTwoPtrOutputWithContext(context.Background())
}

func (i VariantTwoArgs) ToVariantTwoPtrOutputWithContext(ctx context.Context) VariantTwoPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VariantTwoOutput).ToVariantTwoPtrOutputWithContext(ctx)
}

// VariantTwoPtrInput is an input type that accepts VariantTwoArgs, VariantTwoPtr and VariantTwoPtrOutput values.
// You can construct a concrete instance of `VariantTwoPtrInput` via:
//
//	        VariantTwoArgs{...}
//
//	or:
//
//	        nil
type VariantTwoPtrInput interface {
	pulumi.Input

	ToVariantTwoPtrOutput() VariantTwoPtrOutput
	ToVariantTwoPtrOutputWithContext(context.Context) VariantTwoPtrOutput
}

type variantTwoPtrType VariantTwoArgs

func VariantTwoPtr(v *VariantTwoArgs) VariantTwoPtrInput {
	return (*variantTwoPtrType)(v)
}

func (*variantTwoPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**VariantTwo)(nil)).Elem()
}

func (i *variantTwoPtrType) ToVariantTwoPtrOutput() VariantTwoPtrOutput {
	return i.ToVariantTwoPtrOutputWithContext(context.Background())
}

func (i *variantTwoPtrType) ToVariantTwoPtrOutputWithContext(ctx context.Context) VariantTwoPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VariantTwoPtrOutput)
}

type VariantTwoOutput struct{ *pulumi.OutputState }

func (VariantTwoOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*VariantTwo)(nil)).Elem()
}

func (o VariantTwoOutput) ToVariantTwoOutput() VariantTwoOutput {
	return o
}

func (o VariantTwoOutput) ToVariantTwoOutputWithContext(ctx context.Context) VariantTwoOutput {
	return o
}

func (o VariantTwoOutput) ToVariantTwoPtrOutput() VariantTwoPtrOutput {
	return o.ToVariantTwoPtrOutputWithContext(context.Background())
}

func (o VariantTwoOutput) ToVariantTwoPtrOutputWithContext(ctx context.Context) VariantTwoPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v VariantTwo) *VariantTwo {
		return &v
	}).(VariantTwoPtrOutput)
}

func (o VariantTwoOutput) DiscriminantKind() pulumi.StringOutput {
	return o.ApplyT(func(v VariantTwo) string { return v.DiscriminantKind }).(pulumi.StringOutput)
}

func (o VariantTwoOutput) Field2() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VariantTwo) *string { return v.Field2 }).(pulumi.StringPtrOutput)
}

type VariantTwoPtrOutput struct{ *pulumi.OutputState }

func (VariantTwoPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**VariantTwo)(nil)).Elem()
}

func (o VariantTwoPtrOutput) ToVariantTwoPtrOutput() VariantTwoPtrOutput {
	return o
}

func (o VariantTwoPtrOutput) ToVariantTwoPtrOutputWithContext(ctx context.Context) VariantTwoPtrOutput {
	return o
}

func (o VariantTwoPtrOutput) Elem() VariantTwoOutput {
	return o.ApplyT(func(v *VariantTwo) VariantTwo {
		if v != nil {
			return *v
		}
		var ret VariantTwo
		return ret
	}).(VariantTwoOutput)
}

func (o VariantTwoPtrOutput) DiscriminantKind() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VariantTwo) *string {
		if v == nil {
			return nil
		}
		return &v.DiscriminantKind
	}).(pulumi.StringPtrOutput)
}

func (o VariantTwoPtrOutput) Field2() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VariantTwo) *string {
		if v == nil {
			return nil
		}
		return v.Field2
	}).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*VariantOneInput)(nil)).Elem(), VariantOneArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*VariantOnePtrInput)(nil)).Elem(), VariantOneArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*VariantTwoInput)(nil)).Elem(), VariantTwoArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*VariantTwoPtrInput)(nil)).Elem(), VariantTwoArgs{})
	pulumi.RegisterOutputType(VariantOneOutput{})
	pulumi.RegisterOutputType(VariantOnePtrOutput{})
	pulumi.RegisterOutputType(VariantTwoOutput{})
	pulumi.RegisterOutputType(VariantTwoPtrOutput{})
}
