// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package keywords

import (
	"context"
	"reflect"

	"errors"
	"example.com/pulumi-keywords/sdk/go/v20/keywords/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Lambda struct {
	pulumi.CustomResourceState

	Builtins pulumi.StringOutput `pulumi:"builtins"`
	Lambda   pulumi.StringOutput `pulumi:"lambda"`
	Property pulumi.StringOutput `pulumi:"property"`
}

// NewLambda registers a new resource with the given unique name, arguments, and options.
func NewLambda(ctx *pulumi.Context,
	name string, args *LambdaArgs, opts ...pulumi.ResourceOption) (*Lambda, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Builtins == nil {
		return nil, errors.New("invalid value for required argument 'Builtins'")
	}
	if args.Lambda == nil {
		return nil, errors.New("invalid value for required argument 'Lambda'")
	}
	if args.Property == nil {
		return nil, errors.New("invalid value for required argument 'Property'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Lambda
	err := ctx.RegisterResource("keywords:index:Lambda", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetLambda gets an existing Lambda resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetLambda(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *LambdaState, opts ...pulumi.ResourceOption) (*Lambda, error) {
	var resource Lambda
	err := ctx.ReadResource("keywords:index:Lambda", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Lambda resources.
type lambdaState struct {
}

type LambdaState struct {
}

func (LambdaState) ElementType() reflect.Type {
	return reflect.TypeOf((*lambdaState)(nil)).Elem()
}

type lambdaArgs struct {
	Builtins string `pulumi:"builtins"`
	Lambda   string `pulumi:"lambda"`
	Property string `pulumi:"property"`
}

// The set of arguments for constructing a Lambda resource.
type LambdaArgs struct {
	Builtins pulumi.StringInput
	Lambda   pulumi.StringInput
	Property pulumi.StringInput
}

func (LambdaArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*lambdaArgs)(nil)).Elem()
}

type LambdaInput interface {
	pulumi.Input

	ToLambdaOutput() LambdaOutput
	ToLambdaOutputWithContext(ctx context.Context) LambdaOutput
}

func (*Lambda) ElementType() reflect.Type {
	return reflect.TypeOf((**Lambda)(nil)).Elem()
}

func (i *Lambda) ToLambdaOutput() LambdaOutput {
	return i.ToLambdaOutputWithContext(context.Background())
}

func (i *Lambda) ToLambdaOutputWithContext(ctx context.Context) LambdaOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LambdaOutput)
}

type LambdaOutput struct{ *pulumi.OutputState }

func (LambdaOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Lambda)(nil)).Elem()
}

func (o LambdaOutput) ToLambdaOutput() LambdaOutput {
	return o
}

func (o LambdaOutput) ToLambdaOutputWithContext(ctx context.Context) LambdaOutput {
	return o
}

func (o LambdaOutput) Builtins() pulumi.StringOutput {
	return o.ApplyT(func(v *Lambda) pulumi.StringOutput { return v.Builtins }).(pulumi.StringOutput)
}

func (o LambdaOutput) Lambda() pulumi.StringOutput {
	return o.ApplyT(func(v *Lambda) pulumi.StringOutput { return v.Lambda }).(pulumi.StringOutput)
}

func (o LambdaOutput) Property() pulumi.StringOutput {
	return o.ApplyT(func(v *Lambda) pulumi.StringOutput { return v.Property }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*LambdaInput)(nil)).Elem(), &Lambda{})
	pulumi.RegisterOutputType(LambdaOutput{})
}
