# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'FunResult',
    'AwaitableFunResult',
    'fun',
    'fun_output',
]

@pulumi.output_type
class FunResult:
    def __init__(__self__, out=None):
        if out and not isinstance(out, bool):
            raise TypeError("Expected argument 'out' to be a bool")
        pulumi.set(__self__, "out", out)

    @_builtins.property
    @pulumi.getter
    def out(self) -> _builtins.bool:
        """
        Will be the opposite of {{$ ref #/functions/docs:index:fun/inputs/properties/in $}} can be used to set {{$ ref #/resources/docs:index:Resource/inputProperties/in $}}.
        """
        return pulumi.get(self, "out")


class AwaitableFunResult(FunResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return FunResult(
            out=self.out)


def fun(in_: Optional[_builtins.bool] = None,
        opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableFunResult:
    """
    {{$ ref #/functions/docs:index:fun $}} is a basic function for setting {{$ ref #/resources/docs:index:Resource/properties/in $}} on {{$ ref #/resources/docs:index:Resource $}}.


    :param _builtins.bool in_: Will be used to set {{$ ref #/functions/docs:index:fun/outputs/properties/out $}}.
    """
    __args__ = dict()
    __args__['in'] = in_
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('docs:index:fun', __args__, opts=opts, typ=FunResult).value

    return AwaitableFunResult(
        out=pulumi.get(__ret__, 'out'))
def fun_output(in_: Optional[pulumi.Input[_builtins.bool]] = None,
               opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[FunResult]:
    """
    {{$ ref #/functions/docs:index:fun $}} is a basic function for setting {{$ ref #/resources/docs:index:Resource/properties/in $}} on {{$ ref #/resources/docs:index:Resource $}}.


    :param _builtins.bool in_: Will be used to set {{$ ref #/functions/docs:index:fun/outputs/properties/out $}}.
    """
    __args__ = dict()
    __args__['in'] = in_
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('docs:index:fun', __args__, opts=opts, typ=FunResult)
    return __ret__.apply(lambda __response__: FunResult(
        out=pulumi.get(__response__, 'out')))
