# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import builtins
from enum import Enum

__all__ = [
    'ExampleEnum',
    'ExampleEnumInput',
    'ResourceType',
]


class ExampleEnum(builtins.str, Enum):
    ONE = "one"
    TWO = "two"


class ExampleEnumInput(builtins.str, Enum):
    ONE = "one"
    TWO = "two"


class ResourceType(builtins.str, Enum):
    HAHA = "haha"
    BUSINESS = "business"
