# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    'CloudAuditOptionsLogName',
    'ContainerBrightness',
    'ContainerColor',
    'ContainerSize',
]


@pulumi.type_token("plant::CloudAuditOptionsLogName")
class CloudAuditOptionsLogName(_builtins.str, Enum):
    """
    The log_name to populate in the Cloud Audit Record. This is added to regress pulumi/pulumi issue #7913
    """
    UNSPECIFIED_LOG_NAME = "UNSPECIFIED_LOG_NAME"
    """
    Default. Should not be used.
    """
    ADMIN_ACTIVITY = "ADMIN_ACTIVITY"
    """
    Corresponds to "cloudaudit.googleapis.com/activity"
    """
    DATA_ACCESS = "DATA_ACCESS"
    """
    Corresponds to "cloudaudit.googleapis.com/data_access"
    """
    SYNTHETIC = "SYNTHETIC"
    """
    What if triple quotes \"\"\" are used in the description
    """


@pulumi.type_token("plant::ContainerBrightness")
class ContainerBrightness(_builtins.float, Enum):
    ZERO_POINT_ONE = 0.1
    ONE = 1


@pulumi.type_token("plant::ContainerColor")
class ContainerColor(_builtins.str, Enum):
    """
    plant container colors
    """
    RED = "red"
    BLUE = "blue"
    YELLOW = "yellow"


@pulumi.type_token("plant::ContainerSize")
class ContainerSize(_builtins.int, Enum):
    """
    plant container sizes
    """
    FOUR_INCH = 4
    SIX_INCH = 6
    EIGHT_INCH = 8
