# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities
from ._enums import *

__all__ = [
    'ObjArgs',
]

@pulumi.input_type
class ObjArgs:
    def __init__(__self__, *,
                 choice: pulumi.Input[Optional['Choice']] = None,
                 label: pulumi.Input[Optional[_builtins.str]] = None):
        if choice is not None:
            pulumi.set(__self__, "choice", choice)
        if label is not None:
            pulumi.set(__self__, "label", label)

    @_builtins.property
    @pulumi.getter
    def choice(self) -> pulumi.Input[Optional['Choice']]:
        return pulumi.get(self, "choice")

    @choice.setter
    def choice(self, value: pulumi.Input[Optional['Choice']]):
        pulumi.set(self, "choice", value)

    @_builtins.property
    @pulumi.getter
    def label(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "label")

    @label.setter
    def label(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "label", value)


