#!/usr/bin/env python
# coding=utf-8

# Copyright 2017 Pulumi, Inc. All rights reserved.

"""Coconut's Python compiler."""

import argparse
from cocopy.lib import compiler
import json
import pythonparser
import sys

parser = argparse.ArgumentParser()
parser.add_argument("file", help="CocoPy filename")

def main(args):
    pkg = compiler.compile(args.file)
    print(json.dumps(pkg.__dict__))

if __name__ == "__main__":
    sys.exit(main(parser.parse_args()))

