// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:

export { PersonArgs } from "./person";
export type Person = import("./person").Person;
export const Person: typeof import("./person").Person = null as any
utilities.lazy_load_property(exports, "./person", "Person");


export { PetArgs } from "./pet";
export type Pet = import("./pet").Pet;
export const Pet: typeof import("./pet").Pet = null as any
utilities.lazy_load_property(exports, "./pet", "Pet");


export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any
utilities.lazy_load_property(exports, "./provider", "Provider");


// Export sub-modules (modContext.genIndex):
import * as types from "./types";

export {
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "example::Person":
                return new Person(name, <any>undefined, { urn })
            case "example::Pet":
                return new Pet(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("example", "", _module)
pulumi.runtime.registerResourcePackage("example", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:example") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
