import Formal.Types

/-!
Decidable equality for `Ty`. Lean cannot derive `DecidableEq` for a nested
inductive type, so this file spells it out. Nothing here is part of the rules.
-/

namespace Formal

mutual
def Ty.decEq : (a b : Ty) → Decidable (a = b)
  | .bool, .bool => isTrue rfl
  | .int, .int => isTrue rfl
  | .number, .number => isTrue rfl
  | .string, .string => isTrue rfl
  | .id, .id => isTrue rfl
  | .dynamic, .dynamic => isTrue rfl
  | .none, .none => isTrue rfl
  | .const v, .const w =>
    match decEq v w with
    | isTrue h => isTrue (by rw [h])
    | isFalse h => isFalse (by intro e; cases e; exact h rfl)
  | .enum t b vs, .enum t' b' vs' =>
    match decEq t t', Ty.decEq b b', decEq vs vs' with
    | isTrue h0, isTrue h1, isTrue h2 => isTrue (by rw [h0, h1, h2])
    | isFalse h0, _, _ => isFalse (by intro e; cases e; exact h0 rfl)
    | _, isFalse h1, _ => isFalse (by intro e; cases e; exact h1 rfl)
    | _, _, isFalse h2 => isFalse (by intro e; cases e; exact h2 rfl)
  | .list a, .list b =>
    match Ty.decEq a b with
    | isTrue h => isTrue (by rw [h])
    | isFalse h => isFalse (by intro e; cases e; exact h rfl)
  | .set a, .set b =>
    match Ty.decEq a b with
    | isTrue h => isTrue (by rw [h])
    | isFalse h => isFalse (by intro e; cases e; exact h rfl)
  | .map a, .map b =>
    match Ty.decEq a b with
    | isTrue h => isTrue (by rw [h])
    | isFalse h => isFalse (by intro e; cases e; exact h rfl)
  | .tuple as, .tuple bs =>
    match decEqList as bs with
    | isTrue h => isTrue (by rw [h])
    | isFalse h => isFalse (by intro e; cases e; exact h rfl)
  | .object as, .object bs =>
    match decEqProps as bs with
    | isTrue h => isTrue (by rw [h])
    | isFalse h => isFalse (by intro e; cases e; exact h rfl)
  | .union as, .union bs =>
    match decEqList as bs with
    | isTrue h => isTrue (by rw [h])
    | isFalse h => isFalse (by intro e; cases e; exact h rfl)
  | .output a, .output b =>
    match Ty.decEq a b with
    | isTrue h => isTrue (by rw [h])
    | isFalse h => isFalse (by intro e; cases e; exact h rfl)
  | .promise a, .promise b =>
    match Ty.decEq a b with
    | isTrue h => isTrue (by rw [h])
    | isFalse h => isFalse (by intro e; cases e; exact h rfl)
  | .bool, .int => isFalse nofun
  | .bool, .number => isFalse nofun
  | .bool, .string => isFalse nofun
  | .bool, .id => isFalse nofun
  | .bool, .dynamic => isFalse nofun
  | .bool, .none => isFalse nofun
  | .bool, .const _ => isFalse nofun
  | .bool, .enum _ _ _ => isFalse nofun
  | .bool, .list _ => isFalse nofun
  | .bool, .set _ => isFalse nofun
  | .bool, .map _ => isFalse nofun
  | .bool, .tuple _ => isFalse nofun
  | .bool, .object _ => isFalse nofun
  | .bool, .union _ => isFalse nofun
  | .bool, .output _ => isFalse nofun
  | .bool, .promise _ => isFalse nofun
  | .int, .bool => isFalse nofun
  | .int, .number => isFalse nofun
  | .int, .string => isFalse nofun
  | .int, .id => isFalse nofun
  | .int, .dynamic => isFalse nofun
  | .int, .none => isFalse nofun
  | .int, .const _ => isFalse nofun
  | .int, .enum _ _ _ => isFalse nofun
  | .int, .list _ => isFalse nofun
  | .int, .set _ => isFalse nofun
  | .int, .map _ => isFalse nofun
  | .int, .tuple _ => isFalse nofun
  | .int, .object _ => isFalse nofun
  | .int, .union _ => isFalse nofun
  | .int, .output _ => isFalse nofun
  | .int, .promise _ => isFalse nofun
  | .number, .bool => isFalse nofun
  | .number, .int => isFalse nofun
  | .number, .string => isFalse nofun
  | .number, .id => isFalse nofun
  | .number, .dynamic => isFalse nofun
  | .number, .none => isFalse nofun
  | .number, .const _ => isFalse nofun
  | .number, .enum _ _ _ => isFalse nofun
  | .number, .list _ => isFalse nofun
  | .number, .set _ => isFalse nofun
  | .number, .map _ => isFalse nofun
  | .number, .tuple _ => isFalse nofun
  | .number, .object _ => isFalse nofun
  | .number, .union _ => isFalse nofun
  | .number, .output _ => isFalse nofun
  | .number, .promise _ => isFalse nofun
  | .string, .bool => isFalse nofun
  | .string, .int => isFalse nofun
  | .string, .number => isFalse nofun
  | .string, .id => isFalse nofun
  | .string, .dynamic => isFalse nofun
  | .string, .none => isFalse nofun
  | .string, .const _ => isFalse nofun
  | .string, .enum _ _ _ => isFalse nofun
  | .string, .list _ => isFalse nofun
  | .string, .set _ => isFalse nofun
  | .string, .map _ => isFalse nofun
  | .string, .tuple _ => isFalse nofun
  | .string, .object _ => isFalse nofun
  | .string, .union _ => isFalse nofun
  | .string, .output _ => isFalse nofun
  | .string, .promise _ => isFalse nofun
  | .id, .bool => isFalse nofun
  | .id, .int => isFalse nofun
  | .id, .number => isFalse nofun
  | .id, .string => isFalse nofun
  | .id, .dynamic => isFalse nofun
  | .id, .none => isFalse nofun
  | .id, .const _ => isFalse nofun
  | .id, .enum _ _ _ => isFalse nofun
  | .id, .list _ => isFalse nofun
  | .id, .set _ => isFalse nofun
  | .id, .map _ => isFalse nofun
  | .id, .tuple _ => isFalse nofun
  | .id, .object _ => isFalse nofun
  | .id, .union _ => isFalse nofun
  | .id, .output _ => isFalse nofun
  | .id, .promise _ => isFalse nofun
  | .dynamic, .bool => isFalse nofun
  | .dynamic, .int => isFalse nofun
  | .dynamic, .number => isFalse nofun
  | .dynamic, .string => isFalse nofun
  | .dynamic, .id => isFalse nofun
  | .dynamic, .none => isFalse nofun
  | .dynamic, .const _ => isFalse nofun
  | .dynamic, .enum _ _ _ => isFalse nofun
  | .dynamic, .list _ => isFalse nofun
  | .dynamic, .set _ => isFalse nofun
  | .dynamic, .map _ => isFalse nofun
  | .dynamic, .tuple _ => isFalse nofun
  | .dynamic, .object _ => isFalse nofun
  | .dynamic, .union _ => isFalse nofun
  | .dynamic, .output _ => isFalse nofun
  | .dynamic, .promise _ => isFalse nofun
  | .none, .bool => isFalse nofun
  | .none, .int => isFalse nofun
  | .none, .number => isFalse nofun
  | .none, .string => isFalse nofun
  | .none, .id => isFalse nofun
  | .none, .dynamic => isFalse nofun
  | .none, .const _ => isFalse nofun
  | .none, .enum _ _ _ => isFalse nofun
  | .none, .list _ => isFalse nofun
  | .none, .set _ => isFalse nofun
  | .none, .map _ => isFalse nofun
  | .none, .tuple _ => isFalse nofun
  | .none, .object _ => isFalse nofun
  | .none, .union _ => isFalse nofun
  | .none, .output _ => isFalse nofun
  | .none, .promise _ => isFalse nofun
  | .const _, .bool => isFalse nofun
  | .const _, .int => isFalse nofun
  | .const _, .number => isFalse nofun
  | .const _, .string => isFalse nofun
  | .const _, .id => isFalse nofun
  | .const _, .dynamic => isFalse nofun
  | .const _, .none => isFalse nofun
  | .const _, .enum _ _ _ => isFalse nofun
  | .const _, .list _ => isFalse nofun
  | .const _, .set _ => isFalse nofun
  | .const _, .map _ => isFalse nofun
  | .const _, .tuple _ => isFalse nofun
  | .const _, .object _ => isFalse nofun
  | .const _, .union _ => isFalse nofun
  | .const _, .output _ => isFalse nofun
  | .const _, .promise _ => isFalse nofun
  | .enum _ _ _, .bool => isFalse nofun
  | .enum _ _ _, .int => isFalse nofun
  | .enum _ _ _, .number => isFalse nofun
  | .enum _ _ _, .string => isFalse nofun
  | .enum _ _ _, .id => isFalse nofun
  | .enum _ _ _, .dynamic => isFalse nofun
  | .enum _ _ _, .none => isFalse nofun
  | .enum _ _ _, .const _ => isFalse nofun
  | .enum _ _ _, .list _ => isFalse nofun
  | .enum _ _ _, .set _ => isFalse nofun
  | .enum _ _ _, .map _ => isFalse nofun
  | .enum _ _ _, .tuple _ => isFalse nofun
  | .enum _ _ _, .object _ => isFalse nofun
  | .enum _ _ _, .union _ => isFalse nofun
  | .enum _ _ _, .output _ => isFalse nofun
  | .enum _ _ _, .promise _ => isFalse nofun
  | .list _, .bool => isFalse nofun
  | .list _, .int => isFalse nofun
  | .list _, .number => isFalse nofun
  | .list _, .string => isFalse nofun
  | .list _, .id => isFalse nofun
  | .list _, .dynamic => isFalse nofun
  | .list _, .none => isFalse nofun
  | .list _, .const _ => isFalse nofun
  | .list _, .enum _ _ _ => isFalse nofun
  | .list _, .set _ => isFalse nofun
  | .list _, .map _ => isFalse nofun
  | .list _, .tuple _ => isFalse nofun
  | .list _, .object _ => isFalse nofun
  | .list _, .union _ => isFalse nofun
  | .list _, .output _ => isFalse nofun
  | .list _, .promise _ => isFalse nofun
  | .set _, .bool => isFalse nofun
  | .set _, .int => isFalse nofun
  | .set _, .number => isFalse nofun
  | .set _, .string => isFalse nofun
  | .set _, .id => isFalse nofun
  | .set _, .dynamic => isFalse nofun
  | .set _, .none => isFalse nofun
  | .set _, .const _ => isFalse nofun
  | .set _, .enum _ _ _ => isFalse nofun
  | .set _, .list _ => isFalse nofun
  | .set _, .map _ => isFalse nofun
  | .set _, .tuple _ => isFalse nofun
  | .set _, .object _ => isFalse nofun
  | .set _, .union _ => isFalse nofun
  | .set _, .output _ => isFalse nofun
  | .set _, .promise _ => isFalse nofun
  | .map _, .bool => isFalse nofun
  | .map _, .int => isFalse nofun
  | .map _, .number => isFalse nofun
  | .map _, .string => isFalse nofun
  | .map _, .id => isFalse nofun
  | .map _, .dynamic => isFalse nofun
  | .map _, .none => isFalse nofun
  | .map _, .const _ => isFalse nofun
  | .map _, .enum _ _ _ => isFalse nofun
  | .map _, .list _ => isFalse nofun
  | .map _, .set _ => isFalse nofun
  | .map _, .tuple _ => isFalse nofun
  | .map _, .object _ => isFalse nofun
  | .map _, .union _ => isFalse nofun
  | .map _, .output _ => isFalse nofun
  | .map _, .promise _ => isFalse nofun
  | .tuple _, .bool => isFalse nofun
  | .tuple _, .int => isFalse nofun
  | .tuple _, .number => isFalse nofun
  | .tuple _, .string => isFalse nofun
  | .tuple _, .id => isFalse nofun
  | .tuple _, .dynamic => isFalse nofun
  | .tuple _, .none => isFalse nofun
  | .tuple _, .const _ => isFalse nofun
  | .tuple _, .enum _ _ _ => isFalse nofun
  | .tuple _, .list _ => isFalse nofun
  | .tuple _, .set _ => isFalse nofun
  | .tuple _, .map _ => isFalse nofun
  | .tuple _, .object _ => isFalse nofun
  | .tuple _, .union _ => isFalse nofun
  | .tuple _, .output _ => isFalse nofun
  | .tuple _, .promise _ => isFalse nofun
  | .object _, .bool => isFalse nofun
  | .object _, .int => isFalse nofun
  | .object _, .number => isFalse nofun
  | .object _, .string => isFalse nofun
  | .object _, .id => isFalse nofun
  | .object _, .dynamic => isFalse nofun
  | .object _, .none => isFalse nofun
  | .object _, .const _ => isFalse nofun
  | .object _, .enum _ _ _ => isFalse nofun
  | .object _, .list _ => isFalse nofun
  | .object _, .set _ => isFalse nofun
  | .object _, .map _ => isFalse nofun
  | .object _, .tuple _ => isFalse nofun
  | .object _, .union _ => isFalse nofun
  | .object _, .output _ => isFalse nofun
  | .object _, .promise _ => isFalse nofun
  | .union _, .bool => isFalse nofun
  | .union _, .int => isFalse nofun
  | .union _, .number => isFalse nofun
  | .union _, .string => isFalse nofun
  | .union _, .id => isFalse nofun
  | .union _, .dynamic => isFalse nofun
  | .union _, .none => isFalse nofun
  | .union _, .const _ => isFalse nofun
  | .union _, .enum _ _ _ => isFalse nofun
  | .union _, .list _ => isFalse nofun
  | .union _, .set _ => isFalse nofun
  | .union _, .map _ => isFalse nofun
  | .union _, .tuple _ => isFalse nofun
  | .union _, .object _ => isFalse nofun
  | .union _, .output _ => isFalse nofun
  | .union _, .promise _ => isFalse nofun
  | .output _, .bool => isFalse nofun
  | .output _, .int => isFalse nofun
  | .output _, .number => isFalse nofun
  | .output _, .string => isFalse nofun
  | .output _, .id => isFalse nofun
  | .output _, .dynamic => isFalse nofun
  | .output _, .none => isFalse nofun
  | .output _, .const _ => isFalse nofun
  | .output _, .enum _ _ _ => isFalse nofun
  | .output _, .list _ => isFalse nofun
  | .output _, .set _ => isFalse nofun
  | .output _, .map _ => isFalse nofun
  | .output _, .tuple _ => isFalse nofun
  | .output _, .object _ => isFalse nofun
  | .output _, .union _ => isFalse nofun
  | .output _, .promise _ => isFalse nofun
  | .promise _, .bool => isFalse nofun
  | .promise _, .int => isFalse nofun
  | .promise _, .number => isFalse nofun
  | .promise _, .string => isFalse nofun
  | .promise _, .id => isFalse nofun
  | .promise _, .dynamic => isFalse nofun
  | .promise _, .none => isFalse nofun
  | .promise _, .const _ => isFalse nofun
  | .promise _, .enum _ _ _ => isFalse nofun
  | .promise _, .list _ => isFalse nofun
  | .promise _, .set _ => isFalse nofun
  | .promise _, .map _ => isFalse nofun
  | .promise _, .tuple _ => isFalse nofun
  | .promise _, .object _ => isFalse nofun
  | .promise _, .union _ => isFalse nofun
  | .promise _, .output _ => isFalse nofun
def decEqList : (as bs : List Ty) → Decidable (as = bs)
  | [], [] => isTrue rfl
  | a :: as, b :: bs =>
    match Ty.decEq a b, decEqList as bs with
    | isTrue h1, isTrue h2 => isTrue (by rw [h1, h2])
    | isFalse h1, _ => isFalse (by intro e; cases e; exact h1 rfl)
    | _, isFalse h2 => isFalse (by intro e; cases e; exact h2 rfl)
  | [], _ :: _ => isFalse nofun
  | _ :: _, [] => isFalse nofun
def decEqProps : (as bs : List (String × Ty)) → Decidable (as = bs)
  | [], [] => isTrue rfl
  | (k, a) :: as, (l, b) :: bs =>
    match decEq k l, Ty.decEq a b, decEqProps as bs with
    | isTrue h0, isTrue h1, isTrue h2 => isTrue (by rw [h0, h1, h2])
    | isFalse h0, _, _ => isFalse (by intro e; cases e; exact h0 rfl)
    | _, isFalse h1, _ => isFalse (by intro e; cases e; exact h1 rfl)
    | _, _, isFalse h2 => isFalse (by intro e; cases e; exact h2 rfl)
  | [], _ :: _ => isFalse nofun
  | _ :: _, [] => isFalse nofun
end

instance : DecidableEq Ty := Ty.decEq

end Formal
