// Copyright 2016, Pulumi Corporation.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.5
// source: pulumi/converter.proto

package pulumirpc

import (
	codegen "github.com/pulumi/pulumi/sdk/v3/proto/go/codegen"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConvertStateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the gRPC target of the mapper service.
	MapperTarget string `protobuf:"bytes,1,opt,name=mapper_target,json=mapperTarget,proto3" json:"mapper_target,omitempty"`
	// the args passed to `pulumi import` for this conversion. Normally used to specifiy a state file to
	// import from.
	Args          []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertStateRequest) Reset() {
	*x = ConvertStateRequest{}
	mi := &file_pulumi_converter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertStateRequest) ProtoMessage() {}

func (x *ConvertStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pulumi_converter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertStateRequest.ProtoReflect.Descriptor instead.
func (*ConvertStateRequest) Descriptor() ([]byte, []int) {
	return file_pulumi_converter_proto_rawDescGZIP(), []int{0}
}

func (x *ConvertStateRequest) GetMapperTarget() string {
	if x != nil {
		return x.MapperTarget
	}
	return ""
}

func (x *ConvertStateRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

// A ResourceImport specifies a resource to import.
type ResourceImport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the type token for the resource.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// the name of the resource.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// the ID of the resource.
	Id string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	// the provider version to use for the resource, if any.
	Version string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	// the provider PluginDownloadURL to use for the resource, if any.
	PluginDownloadURL string `protobuf:"bytes,5,opt,name=pluginDownloadURL,proto3" json:"pluginDownloadURL,omitempty"`
	// the logical name of the resource.
	LogicalName string `protobuf:"bytes,6,opt,name=logical_name,json=logicalName,proto3" json:"logical_name,omitempty"`
	// true if this is a component resource.
	IsComponent bool `protobuf:"varint,7,opt,name=is_component,json=isComponent,proto3" json:"is_component,omitempty"`
	// true if this is a remote resource. Ignored if is_component is false.
	IsRemote bool `protobuf:"varint,8,opt,name=is_remote,json=isRemote,proto3" json:"is_remote,omitempty"`
	// the replacement parameterization to use for the resource's provider, if any. Set when the resource
	// should be imported under a parameterized (e.g. dynamically bridged) provider rather than a plain one.
	Parameterization *ResourceParameterization `protobuf:"bytes,9,opt,name=parameterization,proto3" json:"parameterization,omitempty"`
	// the extension parameterization to apply to the resource's provider, if any. Unlike a replacement
	// parameterization, the resource's own type is in the base provider's package; the extension is a blob
	// applied on top of that provider. Mutually exclusive with parameterization.
	Extension *ResourceExtension `protobuf:"bytes,10,opt,name=extension,proto3" json:"extension,omitempty"`
	// the name of the resource's parent, if any. Must reference the name of another resource in the same
	// response; resources without a parent are parented to the stack root.
	Parent string `protobuf:"bytes,11,opt,name=parent,proto3" json:"parent,omitempty"`
	// the input properties to include when generating code for the resource. Defaults to the resource's
	// required properties.
	Properties []string `protobuf:"bytes,12,rep,name=properties,proto3" json:"properties,omitempty"`
	// the name of the resource's explicit provider, if any. Must reference a key in the response's
	// providers map; resources without a provider are served by an appropriate default provider.
	Provider      string `protobuf:"bytes,13,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceImport) Reset() {
	*x = ResourceImport{}
	mi := &file_pulumi_converter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceImport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceImport) ProtoMessage() {}

func (x *ResourceImport) ProtoReflect() protoreflect.Message {
	mi := &file_pulumi_converter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceImport.ProtoReflect.Descriptor instead.
func (*ResourceImport) Descriptor() ([]byte, []int) {
	return file_pulumi_converter_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceImport) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResourceImport) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceImport) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResourceImport) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ResourceImport) GetPluginDownloadURL() string {
	if x != nil {
		return x.PluginDownloadURL
	}
	return ""
}

func (x *ResourceImport) GetLogicalName() string {
	if x != nil {
		return x.LogicalName
	}
	return ""
}

func (x *ResourceImport) GetIsComponent() bool {
	if x != nil {
		return x.IsComponent
	}
	return false
}

func (x *ResourceImport) GetIsRemote() bool {
	if x != nil {
		return x.IsRemote
	}
	return false
}

func (x *ResourceImport) GetParameterization() *ResourceParameterization {
	if x != nil {
		return x.Parameterization
	}
	return nil
}

func (x *ResourceImport) GetExtension() *ResourceExtension {
	if x != nil {
		return x.Extension
	}
	return nil
}

func (x *ResourceImport) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ResourceImport) GetProperties() []string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *ResourceImport) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

// A ProviderImport describes an explicit provider that imported resources reference. The import process
// will reuse a matching provider already in the stack's state, or create one from these details.
type ProviderImport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the package name of the provider (e.g. "aws"): the created provider resource will have the type
	// "pulumi:providers:<package>". The provider's version, download URL, and any parameterization are
	// taken from the resources that reference it.
	Package string `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	// the configuration inputs for the provider, if known. Absent inputs mean the provider configures
	// itself from its environment. Secret values are marked with Pulumi's standard secret signature.
	Inputs        *structpb.Struct `protobuf:"bytes,2,opt,name=inputs,proto3" json:"inputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderImport) Reset() {
	*x = ProviderImport{}
	mi := &file_pulumi_converter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderImport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderImport) ProtoMessage() {}

func (x *ProviderImport) ProtoReflect() protoreflect.Message {
	mi := &file_pulumi_converter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderImport.ProtoReflect.Descriptor instead.
func (*ProviderImport) Descriptor() ([]byte, []int) {
	return file_pulumi_converter_proto_rawDescGZIP(), []int{2}
}

func (x *ProviderImport) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *ProviderImport) GetInputs() *structpb.Struct {
	if x != nil {
		return x.Inputs
	}
	return nil
}

// A ResourceParameterization describes the base plugin that a resource's parameterized provider is built
// from. The parameterized package name and version are taken from the resource's own type and version.
type ResourceParameterization struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the name of the base plugin to parameterize (e.g. "terraform-provider").
	PluginName string `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	// the version of the base plugin to parameterize.
	PluginVersion string `protobuf:"bytes,2,opt,name=plugin_version,json=pluginVersion,proto3" json:"plugin_version,omitempty"`
	// the parameter value to apply to the base plugin.
	Value         []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceParameterization) Reset() {
	*x = ResourceParameterization{}
	mi := &file_pulumi_converter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceParameterization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceParameterization) ProtoMessage() {}

func (x *ResourceParameterization) ProtoReflect() protoreflect.Message {
	mi := &file_pulumi_converter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceParameterization.ProtoReflect.Descriptor instead.
func (*ResourceParameterization) Descriptor() ([]byte, []int) {
	return file_pulumi_converter_proto_rawDescGZIP(), []int{3}
}

func (x *ResourceParameterization) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *ResourceParameterization) GetPluginVersion() string {
	if x != nil {
		return x.PluginVersion
	}
	return ""
}

func (x *ResourceParameterization) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// A ResourceExtension describes an extension parameterization to apply to a resource's (base) provider.
type ResourceExtension struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the name of the extension package.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// the version of the extension package.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// the parameter value for the extension.
	Value         []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceExtension) Reset() {
	*x = ResourceExtension{}
	mi := &file_pulumi_converter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceExtension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceExtension) ProtoMessage() {}

func (x *ResourceExtension) ProtoReflect() protoreflect.Message {
	mi := &file_pulumi_converter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceExtension.ProtoReflect.Descriptor instead.
func (*ResourceExtension) Descriptor() ([]byte, []int) {
	return file_pulumi_converter_proto_rawDescGZIP(), []int{4}
}

func (x *ResourceExtension) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceExtension) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ResourceExtension) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ConvertStateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// a list of resources to import.
	Resources []*ResourceImport `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	// any diagnostics from state conversion.
	Diagnostics []*codegen.Diagnostic `protobuf:"bytes,2,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	// the explicit providers referenced by resources' provider fields, keyed by the names used in those
	// fields. Each key is also used as the name of the provider resource created during import.
	Providers     map[string]*ProviderImport `protobuf:"bytes,3,rep,name=providers,proto3" json:"providers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertStateResponse) Reset() {
	*x = ConvertStateResponse{}
	mi := &file_pulumi_converter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertStateResponse) ProtoMessage() {}

func (x *ConvertStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pulumi_converter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertStateResponse.ProtoReflect.Descriptor instead.
func (*ConvertStateResponse) Descriptor() ([]byte, []int) {
	return file_pulumi_converter_proto_rawDescGZIP(), []int{5}
}

func (x *ConvertStateResponse) GetResources() []*ResourceImport {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ConvertStateResponse) GetDiagnostics() []*codegen.Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

func (x *ConvertStateResponse) GetProviders() map[string]*ProviderImport {
	if x != nil {
		return x.Providers
	}
	return nil
}

type ConvertProgramRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the source directory containing the program to convert from.
	SourceDirectory string `protobuf:"bytes,1,opt,name=source_directory,json=sourceDirectory,proto3" json:"source_directory,omitempty"`
	// a target directory to write the resulting PCL code and project file to.
	TargetDirectory string `protobuf:"bytes,2,opt,name=target_directory,json=targetDirectory,proto3" json:"target_directory,omitempty"`
	// the gRPC target of the mapper service.
	MapperTarget string `protobuf:"bytes,3,opt,name=mapper_target,json=mapperTarget,proto3" json:"mapper_target,omitempty"`
	// The target of a codegen.LoaderServer to use for loading schemas.
	LoaderTarget string `protobuf:"bytes,4,opt,name=loader_target,json=loaderTarget,proto3" json:"loader_target,omitempty"`
	// the args passed to `pulumi convert` for this conversion. Normally used to specifiy a root file, or conversion options.
	Args []string `protobuf:"bytes,5,rep,name=args,proto3" json:"args,omitempty"`
	// the directory where the final generated project for the eventual destination language will be written.
	// use to determine relative paths of any asset that will be copied over.
	// Do not write files to this directory as these files might be overwritten in
	// the project generation process.
	GeneratedProjectDirectory string `protobuf:"bytes,6,opt,name=generated_project_directory,json=generatedProjectDirectory,proto3" json:"generated_project_directory,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ConvertProgramRequest) Reset() {
	*x = ConvertProgramRequest{}
	mi := &file_pulumi_converter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertProgramRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertProgramRequest) ProtoMessage() {}

func (x *ConvertProgramRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pulumi_converter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertProgramRequest.ProtoReflect.Descriptor instead.
func (*ConvertProgramRequest) Descriptor() ([]byte, []int) {
	return file_pulumi_converter_proto_rawDescGZIP(), []int{6}
}

func (x *ConvertProgramRequest) GetSourceDirectory() string {
	if x != nil {
		return x.SourceDirectory
	}
	return ""
}

func (x *ConvertProgramRequest) GetTargetDirectory() string {
	if x != nil {
		return x.TargetDirectory
	}
	return ""
}

func (x *ConvertProgramRequest) GetMapperTarget() string {
	if x != nil {
		return x.MapperTarget
	}
	return ""
}

func (x *ConvertProgramRequest) GetLoaderTarget() string {
	if x != nil {
		return x.LoaderTarget
	}
	return ""
}

func (x *ConvertProgramRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ConvertProgramRequest) GetGeneratedProjectDirectory() string {
	if x != nil {
		return x.GeneratedProjectDirectory
	}
	return ""
}

type ConvertProgramResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// any diagnostics from code generation.
	Diagnostics   []*codegen.Diagnostic `protobuf:"bytes,1,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertProgramResponse) Reset() {
	*x = ConvertProgramResponse{}
	mi := &file_pulumi_converter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertProgramResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertProgramResponse) ProtoMessage() {}

func (x *ConvertProgramResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pulumi_converter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertProgramResponse.ProtoReflect.Descriptor instead.
func (*ConvertProgramResponse) Descriptor() ([]byte, []int) {
	return file_pulumi_converter_proto_rawDescGZIP(), []int{7}
}

func (x *ConvertProgramResponse) GetDiagnostics() []*codegen.Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

type ConvertSnippetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the source file. This is used for diagnostics.
	Filename string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	// The raw bytes of the source file.
	Source []byte `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	// The target of a codegen.LoaderServer to use for loading schemas.
	TargetLoader string `protobuf:"bytes,3,opt,name=target_loader,json=targetLoader,proto3" json:"target_loader,omitempty"`
	// The package description to load which contains the token.
	Package *codegen.GetSchemaRequest `protobuf:"bytes,4,opt,name=package,proto3" json:"package,omitempty"`
	// The token to use when converting the snippet. This may be a provider token, such as `pulumi:providers:pkg`,
	// a function token, or a resource token.
	Token string `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	// any extra attributes to convert.
	Attributes    map[string]string `protobuf:"bytes,6,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertSnippetRequest) Reset() {
	*x = ConvertSnippetRequest{}
	mi := &file_pulumi_converter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertSnippetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertSnippetRequest) ProtoMessage() {}

func (x *ConvertSnippetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pulumi_converter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertSnippetRequest.ProtoReflect.Descriptor instead.
func (*ConvertSnippetRequest) Descriptor() ([]byte, []int) {
	return file_pulumi_converter_proto_rawDescGZIP(), []int{8}
}

func (x *ConvertSnippetRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ConvertSnippetRequest) GetSource() []byte {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ConvertSnippetRequest) GetTargetLoader() string {
	if x != nil {
		return x.TargetLoader
	}
	return ""
}

func (x *ConvertSnippetRequest) GetPackage() *codegen.GetSchemaRequest {
	if x != nil {
		return x.Package
	}
	return nil
}

func (x *ConvertSnippetRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ConvertSnippetRequest) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type ConvertSnippetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Any diagnostics raised by code generation.
	Diagnostics []*codegen.Diagnostic `protobuf:"bytes,1,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	// The generated PCL filename.
	Filename string `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	// The generated PCL source code.
	Source []byte `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	// any extra attributes to merge into the final pcl result.
	Attributes    map[string]string `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertSnippetResponse) Reset() {
	*x = ConvertSnippetResponse{}
	mi := &file_pulumi_converter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertSnippetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertSnippetResponse) ProtoMessage() {}

func (x *ConvertSnippetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pulumi_converter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertSnippetResponse.ProtoReflect.Descriptor instead.
func (*ConvertSnippetResponse) Descriptor() ([]byte, []int) {
	return file_pulumi_converter_proto_rawDescGZIP(), []int{9}
}

func (x *ConvertSnippetResponse) GetDiagnostics() []*codegen.Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

func (x *ConvertSnippetResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ConvertSnippetResponse) GetSource() []byte {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ConvertSnippetResponse) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_pulumi_converter_proto protoreflect.FileDescriptor

const file_pulumi_converter_proto_rawDesc = "" +
	"\n" +
	"\x16pulumi/converter.proto\x12\tpulumirpc\x1a\x1cgoogle/protobuf/struct.proto\x1a\x18pulumi/codegen/hcl.proto\x1a\x1bpulumi/codegen/loader.proto\"N\n" +
	"\x13ConvertStateRequest\x12#\n" +
	"\rmapper_target\x18\x01 \x01(\tR\fmapperTarget\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\"\xd4\x03\n" +
	"\x0eResourceImport\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12,\n" +
	"\x11pluginDownloadURL\x18\x05 \x01(\tR\x11pluginDownloadURL\x12!\n" +
	"\flogical_name\x18\x06 \x01(\tR\vlogicalName\x12!\n" +
	"\fis_component\x18\a \x01(\bR\visComponent\x12\x1b\n" +
	"\tis_remote\x18\b \x01(\bR\bisRemote\x12O\n" +
	"\x10parameterization\x18\t \x01(\v2#.pulumirpc.ResourceParameterizationR\x10parameterization\x12:\n" +
	"\textension\x18\n" +
	" \x01(\v2\x1c.pulumirpc.ResourceExtensionR\textension\x12\x16\n" +
	"\x06parent\x18\v \x01(\tR\x06parent\x12\x1e\n" +
	"\n" +
	"properties\x18\f \x03(\tR\n" +
	"properties\x12\x1a\n" +
	"\bprovider\x18\r \x01(\tR\bprovider\"[\n" +
	"\x0eProviderImport\x12\x18\n" +
	"\apackage\x18\x01 \x01(\tR\apackage\x12/\n" +
	"\x06inputs\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06inputs\"x\n" +
	"\x18ResourceParameterization\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12%\n" +
	"\x0eplugin_version\x18\x02 \x01(\tR\rpluginVersion\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"W\n" +
	"\x11ResourceExtension\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"\xb7\x02\n" +
	"\x14ConvertStateResponse\x127\n" +
	"\tresources\x18\x01 \x03(\v2\x19.pulumirpc.ResourceImportR\tresources\x12?\n" +
	"\vdiagnostics\x18\x02 \x03(\v2\x1d.pulumirpc.codegen.DiagnosticR\vdiagnostics\x12L\n" +
	"\tproviders\x18\x03 \x03(\v2..pulumirpc.ConvertStateResponse.ProvidersEntryR\tproviders\x1aW\n" +
	"\x0eProvidersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.pulumirpc.ProviderImportR\x05value:\x028\x01\"\x8b\x02\n" +
	"\x15ConvertProgramRequest\x12)\n" +
	"\x10source_directory\x18\x01 \x01(\tR\x0fsourceDirectory\x12)\n" +
	"\x10target_directory\x18\x02 \x01(\tR\x0ftargetDirectory\x12#\n" +
	"\rmapper_target\x18\x03 \x01(\tR\fmapperTarget\x12#\n" +
	"\rloader_target\x18\x04 \x01(\tR\floaderTarget\x12\x12\n" +
	"\x04args\x18\x05 \x03(\tR\x04args\x12>\n" +
	"\x1bgenerated_project_directory\x18\x06 \x01(\tR\x19generatedProjectDirectory\"Y\n" +
	"\x16ConvertProgramResponse\x12?\n" +
	"\vdiagnostics\x18\x01 \x03(\v2\x1d.pulumirpc.codegen.DiagnosticR\vdiagnostics\"\xcc\x02\n" +
	"\x15ConvertSnippetRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x16\n" +
	"\x06source\x18\x02 \x01(\fR\x06source\x12#\n" +
	"\rtarget_loader\x18\x03 \x01(\tR\ftargetLoader\x123\n" +
	"\apackage\x18\x04 \x01(\v2\x19.codegen.GetSchemaRequestR\apackage\x12\x14\n" +
	"\x05token\x18\x05 \x01(\tR\x05token\x12P\n" +
	"\n" +
	"attributes\x18\x06 \x03(\v20.pulumirpc.ConvertSnippetRequest.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9f\x02\n" +
	"\x16ConvertSnippetResponse\x12?\n" +
	"\vdiagnostics\x18\x01 \x03(\v2\x1d.pulumirpc.codegen.DiagnosticR\vdiagnostics\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x16\n" +
	"\x06source\x18\x03 \x01(\fR\x06source\x12Q\n" +
	"\n" +
	"attributes\x18\x04 \x03(\v21.pulumirpc.ConvertSnippetResponse.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x90\x02\n" +
	"\tConverter\x12Q\n" +
	"\fConvertState\x12\x1e.pulumirpc.ConvertStateRequest\x1a\x1f.pulumirpc.ConvertStateResponse\"\x00\x12W\n" +
	"\x0eConvertProgram\x12 .pulumirpc.ConvertProgramRequest\x1a!.pulumirpc.ConvertProgramResponse\"\x00\x12W\n" +
	"\x0eConvertSnippet\x12 .pulumirpc.ConvertSnippetRequest\x1a!.pulumirpc.ConvertSnippetResponse\"\x00B4Z2github.com/pulumi/pulumi/sdk/v3/proto/go;pulumirpcb\x06proto3"

var (
	file_pulumi_converter_proto_rawDescOnce sync.Once
	file_pulumi_converter_proto_rawDescData []byte
)

func file_pulumi_converter_proto_rawDescGZIP() []byte {
	file_pulumi_converter_proto_rawDescOnce.Do(func() {
		file_pulumi_converter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pulumi_converter_proto_rawDesc), len(file_pulumi_converter_proto_rawDesc)))
	})
	return file_pulumi_converter_proto_rawDescData
}

var file_pulumi_converter_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pulumi_converter_proto_goTypes = []any{
	(*ConvertStateRequest)(nil),      // 0: pulumirpc.ConvertStateRequest
	(*ResourceImport)(nil),           // 1: pulumirpc.ResourceImport
	(*ProviderImport)(nil),           // 2: pulumirpc.ProviderImport
	(*ResourceParameterization)(nil), // 3: pulumirpc.ResourceParameterization
	(*ResourceExtension)(nil),        // 4: pulumirpc.ResourceExtension
	(*ConvertStateResponse)(nil),     // 5: pulumirpc.ConvertStateResponse
	(*ConvertProgramRequest)(nil),    // 6: pulumirpc.ConvertProgramRequest
	(*ConvertProgramResponse)(nil),   // 7: pulumirpc.ConvertProgramResponse
	(*ConvertSnippetRequest)(nil),    // 8: pulumirpc.ConvertSnippetRequest
	(*ConvertSnippetResponse)(nil),   // 9: pulumirpc.ConvertSnippetResponse
	nil,                              // 10: pulumirpc.ConvertStateResponse.ProvidersEntry
	nil,                              // 11: pulumirpc.ConvertSnippetRequest.AttributesEntry
	nil,                              // 12: pulumirpc.ConvertSnippetResponse.AttributesEntry
	(*structpb.Struct)(nil),          // 13: google.protobuf.Struct
	(*codegen.Diagnostic)(nil),       // 14: pulumirpc.codegen.Diagnostic
	(*codegen.GetSchemaRequest)(nil), // 15: codegen.GetSchemaRequest
}
var file_pulumi_converter_proto_depIdxs = []int32{
	3,  // 0: pulumirpc.ResourceImport.parameterization:type_name -> pulumirpc.ResourceParameterization
	4,  // 1: pulumirpc.ResourceImport.extension:type_name -> pulumirpc.ResourceExtension
	13, // 2: pulumirpc.ProviderImport.inputs:type_name -> google.protobuf.Struct
	1,  // 3: pulumirpc.ConvertStateResponse.resources:type_name -> pulumirpc.ResourceImport
	14, // 4: pulumirpc.ConvertStateResponse.diagnostics:type_name -> pulumirpc.codegen.Diagnostic
	10, // 5: pulumirpc.ConvertStateResponse.providers:type_name -> pulumirpc.ConvertStateResponse.ProvidersEntry
	14, // 6: pulumirpc.ConvertProgramResponse.diagnostics:type_name -> pulumirpc.codegen.Diagnostic
	15, // 7: pulumirpc.ConvertSnippetRequest.package:type_name -> codegen.GetSchemaRequest
	11, // 8: pulumirpc.ConvertSnippetRequest.attributes:type_name -> pulumirpc.ConvertSnippetRequest.AttributesEntry
	14, // 9: pulumirpc.ConvertSnippetResponse.diagnostics:type_name -> pulumirpc.codegen.Diagnostic
	12, // 10: pulumirpc.ConvertSnippetResponse.attributes:type_name -> pulumirpc.ConvertSnippetResponse.AttributesEntry
	2,  // 11: pulumirpc.ConvertStateResponse.ProvidersEntry.value:type_name -> pulumirpc.ProviderImport
	0,  // 12: pulumirpc.Converter.ConvertState:input_type -> pulumirpc.ConvertStateRequest
	6,  // 13: pulumirpc.Converter.ConvertProgram:input_type -> pulumirpc.ConvertProgramRequest
	8,  // 14: pulumirpc.Converter.ConvertSnippet:input_type -> pulumirpc.ConvertSnippetRequest
	5,  // 15: pulumirpc.Converter.ConvertState:output_type -> pulumirpc.ConvertStateResponse
	7,  // 16: pulumirpc.Converter.ConvertProgram:output_type -> pulumirpc.ConvertProgramResponse
	9,  // 17: pulumirpc.Converter.ConvertSnippet:output_type -> pulumirpc.ConvertSnippetResponse
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_pulumi_converter_proto_init() }
func file_pulumi_converter_proto_init() {
	if File_pulumi_converter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pulumi_converter_proto_rawDesc), len(file_pulumi_converter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pulumi_converter_proto_goTypes,
		DependencyIndexes: file_pulumi_converter_proto_depIdxs,
		MessageInfos:      file_pulumi_converter_proto_msgTypes,
	}.Build()
	File_pulumi_converter_proto = out.File
	file_pulumi_converter_proto_goTypes = nil
	file_pulumi_converter_proto_depIdxs = nil
}
