# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'BarArgs',
]

@pulumi.input_type
class BarArgs:
    def __init__(__self__, *,
                 prop: pulumi.Input[_builtins.str]):
        pulumi.set(__self__, "prop", prop)

    @_builtins.property
    @pulumi.getter
    def prop(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "prop")

    @prop.setter
    def prop(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "prop", value)


