changes:
- type: fix
  scope: sdk/nodejs
  description: Pass secret values as Output objects to resource hooks to properly maintain their secretness. Previously hooks received an internal representation for secret values.
