component: cli/config
kind: feat
body: Add a `--env` flag to `up`, `preview`, `destroy`, and `refresh` to override a stack's imported environment for a single run
time: 2026-06-08T00:00:00.000000+00:00
custom:
    PR: ""
