# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from ._enums import *

__all__ = ['ResourceArgs', 'Resource']

@pulumi.input_type
class ResourceArgs:
    def __init__(__self__, *,
                 the_enum: pulumi.Input['MyEnum'],
                 the_string: pulumi.Input[_builtins.str]):
        """
        The set of arguments for constructing a Resource resource.
        """
        pulumi.set(__self__, "the_enum", the_enum)
        pulumi.set(__self__, "the_string", the_string)

    @_builtins.property
    @pulumi.getter(name="theEnum")
    def the_enum(self) -> pulumi.Input['MyEnum']:
        return pulumi.get(self, "the_enum")

    @the_enum.setter
    def the_enum(self, value: pulumi.Input['MyEnum']):
        pulumi.set(self, "the_enum", value)

    @_builtins.property
    @pulumi.getter(name="theString")
    def the_string(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "the_string")

    @the_string.setter
    def the_string(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "the_string", value)


@pulumi.type_token("config-enum:index:Resource")
class Resource(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 the_enum: pulumi.Input[Optional['MyEnum']] = None,
                 the_string: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Create a Resource resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ResourceArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Resource resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param ResourceArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ResourceArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 the_enum: pulumi.Input[Optional['MyEnum']] = None,
                 the_string: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ResourceArgs.__new__(ResourceArgs)

            if the_enum is None and not opts.urn:
                raise TypeError("Missing required property 'the_enum'")
            __props__.__dict__["the_enum"] = the_enum
            if the_string is None and not opts.urn:
                raise TypeError("Missing required property 'the_string'")
            __props__.__dict__["the_string"] = the_string
        super(Resource, __self__).__init__(
            'config-enum:index:Resource',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'Resource':
        """
        Get an existing Resource resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = ResourceArgs.__new__(ResourceArgs)

        __props__.__dict__["the_enum"] = None
        __props__.__dict__["the_string"] = None
        return Resource(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="theEnum")
    def the_enum(self) -> pulumi.Output['MyEnum']:
        return pulumi.get(self, "the_enum")

    @_builtins.property
    @pulumi.getter(name="theString")
    def the_string(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "the_string")

