// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

import * as pulumiTls from "@pulumi/tls";

export class Component extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType: string = 'foo:index:Component';

    /**
     * Returns true if the given object is an instance of Component (or a subclass of it).  This is
     * designed to work even when multiple copies of the Pulumi SDK have been loaded into the
     * same process.
     */
    public static isInstance(obj: any): obj is Component {
        if (obj === undefined || obj === null) {
            return false;
        }
        if (obj instanceof Component) {
            return true;
        }
        if (obj['__pulumiType'] === Component.__pulumiType) {
            return true;
        }
        const baseTypes = obj?.constructor?.['__pulumiBaseTypes'];
        return Array.isArray(baseTypes) && baseTypes.indexOf(Component.__pulumiType) !== -1;
    }

    declare public readonly eniConfig: pulumi.Output<{[key: string]: outputs.crd.k8s.amazonaws.com.v1alpha1.ENIConfigSpec} | undefined>;
    declare public readonly pod: pulumi.Output<pulumiTls.types.output.CertRequestSubject | undefined>;

    /**
     * Create a Component resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ComponentArgs, opts?: pulumi.ComponentResourceOptions, __chain?: any /* internal */) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (__chain !== undefined) {
            super(__chain.type, name, __chain.inputs, opts, __chain.mode === "generated" /*remote*/);
            return;
        }
        if (new.target !== Component) {
            resourceInputs["eniConfig"] = args?.eniConfig;
            resourceInputs["pod"] = args?.pod;
            opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
            super((new.target as any).__pulumiType, name, resourceInputs, opts, false /*local*/);
            void pulumi.runtime.constructBaseResource(this, "foo:index:Component", args ?? {}, { version: utilities.getVersion() }, ["eniConfig", "pod"]);
            return;
        }
        if (!opts.id) {
            resourceInputs["eniConfig"] = args?.eniConfig;
            resourceInputs["pod"] = args?.pod;
        } else {
            resourceInputs["eniConfig"] = undefined /*out*/;
            resourceInputs["pod"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Component.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a Component resource.
 */
export interface ComponentArgs {
    eniConfig?: pulumi.Input<{[key: string]: pulumi.Input<inputs.crd.k8s.amazonaws.com.v1alpha1.ENIConfigSpecArgs>} | undefined>;
    pod?: pulumi.Input<pulumiTls.types.input.CertRequestSubject | undefined>;
}
