// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Simple extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'conformance-component:index:Simple';

    /**
     * Returns true if the given object is an instance of Simple.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Simple {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Simple.__pulumiType;
    }

    declare public readonly value: pulumi.Output<boolean>;

    /**
     * Create a Simple resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SimpleArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.value === undefined && !opts.urn) {
                throw new Error("Missing required property 'value'");
            }
            resourceInputs["value"] = args?.value;
        } else {
            resourceInputs["value"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Simple.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a Simple resource.
 */
export interface SimpleArgs {
    value: pulumi.Input<boolean>;
}
