name: Lint

on:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            go:
              - '.github/workflows/lint.yml'
              - '**/*.go'
            gomods:
              - '.github/workflows/lint.yml'
              - '**/go.mod'
            python:
              - '.github/workflows/lint.yml'
              - '**/*.py'
            typescript:
              - '.github/workflows/lint.yml'
              - '**/*.js'
              - '**/*.ts'
            actions:
              - '.github/workflows/*'

      # JavaScript / TypeScript

      - if: ${{ steps.changes.outputs.typescript == 'true' }}
        name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - if: ${{ steps.changes.outputs.typescript == 'true' }}
        name: Install dependencies
        run: yarn
        working-directory: ./sdk/nodejs

      - if: ${{ steps.changes.outputs.typescript == 'true' }}
        name: ESLint
        run: yarn eslint --ext .ts .
        working-directory: ./sdk/nodejs

      - if: ${{ steps.changes.outputs.typescript == 'true' }}
        name: Biome
        run: yarn biome ci
        working-directory: ./sdk/nodejs

      # Go

      - if: ${{ steps.changes.outputs.go == 'true' }}
        name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - if: ${{ steps.changes.outputs.go == 'true' }}
        name: Lint Go
        uses: golangci/golangci-lint-action@v6.5.0
        with:
          working-directory: pkg

      # Python

      - if: ${{ steps.changes.outputs.python == 'true' }}
        name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - if: ${{ steps.changes.outputs.python == 'true' }}
        name: Lint Python
        uses: wearerequired/lint-action@v2
        with:
          pylint_dir: ./sdk/python
          pylint: true

      # Actions

      - if: ${{ steps.changes.outputs.actions == 'true' }}
        name: Lint Actions
        uses: devops-actions/actionlint@v0.1.9

      # ... and, last but not least, go.mod

      - if: ${{ steps.changes.outputs.gomods == 'true' }}
        name: Lint go.mod
        uses: evantorrie/mott-the-tidier@v1-beta
        with:
          gomods: |
            **/go.mod
