name: Lint

on:
  pull_request:

jobs:
  node:
    name: Lint NodeJS SDK
    runs-on: ubuntu-22.04
    steps:
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - './github/workflows/lint.yml'
              - './sdk/nodejs/**.ts'

      - run: |
          curl https://mise.run | sh
          echo "$HOME/.local/share/mise/bin"   >> $GITHUB_PATH
          echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH
          echo "MISE_CACHE=$(mise cache)"      >> $GITHUB_ENV
          mise settings experimental=true

      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Mise cache
        id: cache
        uses: actions/cache@v4
        with:
          key: nodejs-${{ runner.os }}
          path: |
            ${{ env.MISE_CACHE }}
            ./sdk/nodejs/node_modules

      - name: Install dependencies
        run: mise run install
        working-directory: "./sdk/nodejs"

      - name: Run Biome
        run: mise run lint
        working-directory: "./sdk/nodejs"
