name: Lint

on:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      # Setup

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Install Node dependencies
        run: yarn
        working-directory: ./sdk/nodejs

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: pip install pylint

      # Linting

      - name: Lint NodeJS
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          eslint_dir: ./sdk/nodejs
          eslint_extensions: ts

          pylint_dir: ./sdk/python
          pylint: true

      - name: Lint Actions
        uses: devops-actions/actionlint@v0.1.9

      - name: Lint go.mod
        uses: evantorrie/mott-the-tidier@v1-beta
        with:
          gomods: |
            **/go.mod
