name: Lint

on:
  pull_request:

jobs:
  node:
    name: Lint NodeJS SDK
    runs-on: ubuntu-22.04
    steps:
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - './github/workflows/lint.yml'
              - './sdk/nodejs/**.ts'

      - run: |
          curl https://mise.run | sh
          echo "$HOME/.local/share/mise/bin"   >> $GITHUB_PATH
          echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH
          echo "MISE_CACHE=$(mise cache)"      >> $GITHUB_ENV
          mise settings experimental=true

      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Mise cache
        uses: actions/cache@v4
        with:
          key: mise-cache-${{ runner.os }}
          path: ~/.local/share/mise

      - name: Node cache
        uses: actions/cache@v4
        with:
          key: sdk-nodejs-cache-${{ runner.os }}
          path: ./sdk/nodejs/node_modules

      - name: Install dependencies
        run: mise run install
        working-directory: "./sdk/nodejs"

      - name: Run linters
        run: mise run lint
        working-directory: "./sdk/nodejs"

  python:
    name: Lint Python SDK
    runs-on: ubuntu-22.04
    steps:
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - './github/workflows/lint.yml'
              - './sdk/python/**.py'

      - run: |
          curl https://mise.run | sh
          echo "$HOME/.local/share/mise/bin"   >> $GITHUB_PATH
          echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH
          echo "MISE_CACHE=$(mise cache)"      >> $GITHUB_ENV
          mise settings experimental=true

      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Mise cache
        uses: actions/cache@v4
        with:
          key: mise-cache-${{ runner.os }}
          path: ~/.local/share/mise

      - name: UV cache
        uses: actions/cache@v4
        with:
          key: sdk-python-cache-${{ runner.os }}
          path: ./sdk/python/.venv

      - name: Install dependencies
        run: mise run install
        working-directory: "./sdk/python"

      - name: Run linters
        run: mise run lint
        working-directory: "./sdk/python"
