name: Release

permissions:
  # To create the follow-up PR.
  contents: write
  pull-requests: write

on:
  release:
    types:
      - released

concurrency: release

jobs:
  info:
    name: gather
    runs-on: ubuntu-latest
    outputs:
      version: "${{ fromJSON(steps.version.outputs.version) }}"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        # Uses release ref (tag)
      - name: Info
        id: version
        run: |
          TAG="${{ github.event.release.tag_name }}"
          PULUMI_VERSION="${TAG#v}" # remove prefix

          ./.github/scripts/set-output version "${PULUMI_VERSION}"

  release:
    name: release
    needs: [info]
    uses: ./.github/workflows/release.yml
    with:
      ref: ${{ github.event.release.tag_name }}
      version: ${{ needs.info.outputs.version }}
      release-notes: ${{ github.event.release.body }}
      queue-merge: true
      run-dispatch-commands: true
    secrets: inherit

  update-dotnet-automation-api:
    name: update-dotnet-automation-api
    runs-on: ubuntu-latest
    steps:
      - name: Trigger pulumi-dotnet automation API update
        env:
          GITHUB_TOKEN: ${{ secrets.PULUMI_BOT_TOKEN }}
        run: |
          gh api repos/pulumi/pulumi-dotnet/dispatches \
            -f event_type=update-automation-api \
            -f "client_payload[ref]=${{ github.event.release.tag_name }}"
