name: New Pull Request
on:
  pull_request_target:

jobs:
  comment-on-pr:
    # We only care about commenting on a PR if the PR is from a fork
    if: github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@1.0.1
        with:
          message: |
            PR is now waiting for a maintainer to run the acceptance tests.

            **Note for the maintainer:** To run the acceptance tests, please comment */run-acceptance-tests* on the PR

            Further commands available:

            * `/run-codegen` - used to test the Pull Request against downstream codegen
            * `/run-docs-gen` - used to test the Pull Request against documentation generation
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
