name: Post-Release PR

permissions:
  # To create a PR
  contents: write
  pull-requests: write

on:
  workflow_call:
    inputs:
      ref:
        required: true
        description: "GitHub ref to use"
        type: string
      version:
        required: true
        description: "Version to produce"
        type: string
      branch_from_ref:
        required: false
        description: "Commit to branch from, if not the tag"
        type: string
      release-notes:
        required: true
        description: "Release notes to publish"
        type: string
      queue-merge:
        required: false
        default: false
        description: "Whether to queue the release for immediate merge"
        type: boolean

jobs:
  version-bump:
    name: version bump
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/retry
        with:
          action: actions/checkout@v6
          with: |
            ref: ${{ inputs.ref }}
          attempt_limit: 3
          attempt_delay: 5000
      - uses: actions/setup-go@v6
        with:
          go-version-file: sdk/go.mod
      - uses: miniscruff/changie-action@v2
        with:
          version: v1.21.0
      - name: Create PR
        env:
          PULUMI_VERSION: ${{ inputs.version }}
          QUEUE_MERGE: ${{ inputs.queue-merge }}
          GITHUB_TOKEN: ${{ secrets.PULUMI_BOT_TOKEN }}
        run: |
          set -euo pipefail
          git switch --create "automation/release-v${PULUMI_VERSION}"

          changie batch "${PULUMI_VERSION}"
          changie merge

          git config user.name github-actions
          git config user.email github-actions@github.com

          git add -A
          git commit -m "chore: changelog for v${PULUMI_VERSION}"

          # Update go module dependencies
          (
            cd pkg
            go get -u "github.com/pulumi/pulumi/sdk/v3@v${PULUMI_VERSION}"
          )
          make tidy_fix
          git add -A
          git commit -m "chore: post-release go.mod updates"

          git push -u origin HEAD

          # Note that the title of the PR is used in the on-push workflow.  If the title needs to
          # change here, please also check on-push.yml
          PR=$(gh pr create --title "Changelog and go.mod updates for v${PULUMI_VERSION}" --body "")

          if [ "${QUEUE_MERGE}" = "true" ]; then
            gh pr merge --auto --squash "${PR}"
          fi
