name: Downstream Resource Docs Test
on:
  pull_request:
    paths:
      - 'pkg/codegen/docs/**'
      - 'pkg/codegen/docs/docs.go'
      - 'pkg/codegen/docs/docs_test.go'
      - '.github/workflows/res-docs-test.yml'

jobs:
  aws:
    name: AWS Resource Docs
    env:
      GOPATH: ${{ github.workspace }}
      TF2PULUMI_VERSION: 0.7.0
      OS: linux
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - name: Add GOBIN to PATH
        run: |
          mkdir -p "$(go env GOPATH)/bin"
          echo "::add-path::$(go env GOPATH)/bin"
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install tf2pulumi
        run: |
          echo "installing Terraform-to-Pulumi conversion tool (${TF2PULUMI_VERSION}-${OS})"
          curl -L "https://github.com/pulumi/tf2pulumi/releases/download/v${TF2PULUMI_VERSION}/tf2pulumi-v${TF2PULUMI_VERSION}-${OS}-x64.tar.gz" | \
                    tar -xvz -C "$(go env GOPATH)/bin"
      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@releases/v1

      - name: Check out source code
        uses: actions/checkout@master
        with:
          path: pulumi
      - name: Check out pulumi-aws
        uses: actions/checkout@master
        with:
          repository: pulumi/pulumi-aws
          path: pulumi-aws
      - name: Check out docs
        uses: actions/checkout@master
        with:
          repository: pulumi/docs
          path: docs

      - name: Regenerate resource docs
        id: regenerate-resource-docs
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          BRANCH_NAME="${GITHUB_ACTOR}/${PR_NUMBER}-test-generator-changes"

          pushd docs
          git checkout -b ${BRANCH_NAME}
          ./scripts/gen_resource_docs.sh aws true
          git add .
          git commit -am "Regenerate AWS docs."
          git rev-parse --abbrev-ref HEAD
          popd

          echo "::set-output name=branchName::${BRANCH_NAME}"
          echo "::set-output name=prNumber::${PR_NUMBER}"
#      - name: Create draft docs PR
#        uses: peter-evans/create-pull-request@v2
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          path: docs
#          commit-message: Regenerate AWS docs
#          title: Preview resource docs changes caused by generator changes
#          body: |
#            This PR was auto-generated from "pulumi/pulumi#${{ steps.regenerate-resource-docs.outputs.prNumber }}"
#          assignees: ${{ github.actor }}
#          draft: true
#          branch: ${{ steps.regenerate-resource-docs.outputs.branchName }}
#          base: master
#          request-to-parent: false

