name: Test Mac OS (Daily)

"on":
  workflow_dispatch: {}
  schedule:
    - cron: 0 8 * * *

jobs:
  versions:
    name: Versions
    uses: ./.github/workflows/versions.yml
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    needs: versions
    with:
      enable-coverage: true
      goreleaser-flags: -p 3 --skip-validate
  test-macos:
    name: Test MacOS
    needs: build
    uses: ./.github/workflows/test.yml
    with:
      enable-coverage: true
      platform: macos-latest
    secrets:
      pulumi-access-token: ${{ secrets.PULUMI_PROD_ACCESS_TOKEN }}
