name: Test Windows (Daily)
"on":
  workflow_dispatch: {}
  schedule:
    - cron: 0 8 * * *

jobs:
  build:
    name: Build
    uses: pulumi/pulumi/.github/workflows/build.yml@master
    with:
      # Cross-compiling from ubuntu-latest is faster but the artifact
      # checksums will not match what publish-binaries expects.
      default-build-platform: macos-latest
      enable-coverage: true
      goreleaser-config: '.goreleaser.prerelease.yml'
      goreleaser-flags: '-p 3 --skip-publish --skip-announce --skip-validate'
  test-macos:
    name: Test MacOS
    needs: build
    uses: pulumi/pulumi/.github/workflows/test.yml@master
    if: github.event_name == 'repository_dispatch' || github.event.pull_request.head.repo.full_name == github.repository
    with:
      enable-coverage: true
      platform: macos-latest
    secrets:
      pulumi-access-token: ${{ secrets.PULUMI_PROD_ACCESS_TOKEN }}
