name: Test Windows (Daily)
"on":
  workflow_dispatch: {}
  schedule:
    - cron: 0 8 * * *

jobs:
  versions:
    name: Versions
    uses: ./.github/workflows/versions.yml
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    needs: versions
    with:
      enable-coverage: true
      goreleaser-flags: -p 3 --skip-validate
      macos-build-platform: ubuntu-latest
  test-windows:
    name: Test Windows
    needs: build
    uses: ./.github/workflows/test.yml
    with:
      enable-coverage: true
      platform: windows-latest
    secrets:
      pulumi-access-token: ${{ secrets.PULUMI_PROD_ACCESS_TOKEN }}
