name: Test Windows (Daily)
"on":
  workflow_dispatch: {}
  schedule:
    - cron: 0 8 * * *

jobs:
  versions:
    name: Versions
    uses: ./.github/workflows/versions.yml
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    needs: versions
    with:
      # Cross-compiling from ubuntu-latest is faster but the artifact
      # checksums will not match what publish-binaries expects.
      default-build-platform: macos-latest
      enable-coverage: true
      goreleaser-config: '.goreleaser.prerelease.yml'
      goreleaser-flags: '-p 3 --skip-publish --skip-announce --skip-validate'
  test-windows:
    name: Test Windows
    needs: build
    uses: ./.github/workflows/test.yml
    if: github.event_name == 'repository_dispatch' || github.event.pull_request.head.repo.full_name == github.repository
    with:
      enable-coverage: true
      platform: windows-latest
    secrets:
      pulumi-access-token: ${{ secrets.PULUMI_PROD_ACCESS_TOKEN }}
