env:
  GITHUB_TOKEN: ${{ secrets.PULUMI_BOT_TOKEN }}
  VERSION: ${{ github.event.client_payload.ref }}
  COMMIT_SHA: ${{ github.event.client_payload.commitSha }}

on:
  repository_dispatch:
    types:
      - homebrew-bump

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - name: Add Homebrew to the PATH
        run: |
          echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> "${GITHUB_PATH}"
      - name: Bump Homebrew formula
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.PULUMI_BOT_HOMEBREW_TOKEN }}
        run: |
          git config --global user.name "Pulumi Bot"
          git config --global user.email "30351955+pulumi-bot@users.noreply.github.com"
          brew developer on
          brew update-reset
          brew tap homebrew/core --force
          brew bump-formula-pr \
            --no-audit \
            --no-browse \
            --tag="v${VERSION}" \
            --revision="${COMMIT_SHA}" \
            pulumi
