#!/bin/sh
# we exploit the fact that the cwd when `pulumi-langhost-nodejs-exec` is
# run is the root of the node program we want to run and use a relative
# path here.
pulumi-langhost-nodejs-node ./node_modules/@pulumi/pulumi/cmd/run $@

